/**
 * @typedef {Object} Chord
 * @property {string} forte-code - The forte code of the chord.
 * @property {Array.<Number>} pitch-classes - An array of pitch classes that the chord is comprised of.
 * @property {string} name - The name of the chord.
 * @property {string | null} carter-number - The Carter number of the chord.
 * @property {string | null} complement-forte-code - The forte code of the complement of the chord.
 * @property {string | null} documentation-link - A link to the documentation for the chord.
 */

const CHORDS = {
  /** @type {Chord[]} */
  data: [
    {
      "forte-code": "3-1",
      "pitch-classes": [0, 1, 2],
      name: "Chromatic tricord",
      "carter-number": "4",
      "complement-forte-code": "9-1",
      "documentation-link": null,
    },
    {
      "forte-code": "3-2",
      "pitch-classes": [0, 1, 3],
      name: "Phrygian triad",
      "carter-number": null,
        "complement-forte-code": "9-2B",
      "documentation-link": null,
    },
    {
      "forte-code": "3-2B",
      "pitch-classes": [0, 2, 3],
      name: "Minor tricord",
      "carter-number": null,
      "complement-forte-code": "9-2A",
      "documentation-link": null,
    },
    {
      "forte-code": "3-3",
      "pitch-classes": [0, 1, 4],
      name: "mMaj7(no5) - (Major/minor triad n1)",
        "carter-number": "11",
        "complement-forte-code": "9-3B",
      "documentation-link": null,
    },
    {
      "forte-code": "3-3B",
      "pitch-classes": [0, 3, 4],
      name: "Major/minor triad n2",
      "carter-number": null,
      "complement-forte-code": "9-3A",
      "documentation-link": null,
    },
    {
      "forte-code": "3-4",
      "pitch-classes": [0, 1, 5],
      name: "Maj7(no5) - incomplete Maj7 n1",
      "carter-number": null,
        "complement-forte-code": "9-4B",
      "documentation-link": null,
    },

    {
      "forte-code": "3-4B",
      "pitch-classes": [0, 4, 5],
      name: "Maj7(no3) - incomplete Maj7 n2",
      "carter-number": null,
      "complement-forte-code": "9-4A",
      "documentation-link": null,
    },
    {
      "forte-code": "3-5",
      "pitch-classes": [0, 1, 6],
      name: "Fourth/Tritone triad - Rite n1 - Lydian triad",
      "carter-number": null,
        "complement-forte-code": "9-5B",
      "documentation-link": null,
    },

    {
      "forte-code": "3-5B",
      "pitch-classes": [0, 5, 6],
      name: "Tritone/Fourth triad - Rite n2 - Phrygian triad n2",
      "carter-number": null,
      "complement-forte-code": "9-5A",
      "documentation-link": null,
    },
    {
      "forte-code": "3-6",
      "pitch-classes": [0, 2, 4],
      name: "Tonal triad",
      "carter-number": "3",
      "complement-forte-code": "9-6",
      "documentation-link": null,
    },
    {
      "forte-code": "3-7",
      "pitch-classes": [0, 2, 5],
      name: "m7(no5) - Incomplete minor seventh triad",
      "carter-number": null,
        "complement-forte-code": "9-7B",
      "documentation-link": null,
    },
    {
      "forte-code": "3-7B",
      "pitch-classes": [0, 3, 5],
      name: "7(no3) - Incomplete dominant triad n1",
      "carter-number": null,
      "complement-forte-code": "9-7A",
      "documentation-link": null,
    },
    {
      "forte-code": "3-8",
      "pitch-classes": [0, 2, 6],
      name: "7(no5) - Incomplete dominant triad n2 - Italian sixth",
      "carter-number": null,
        "complement-forte-code": "9-8B",
      "documentation-link": null,
    },
    {
      "forte-code": "3-8B",
      "pitch-classes": [0, 4, 6],
      name: "5b triad - 1 3 5b ",
      "carter-number": null,
      "complement-forte-code": "9-8A",
      "documentation-link": null,
    },
    {
      "forte-code": "3-9",
      "pitch-classes": [0, 2, 7],
      name: "Quartal triad",
      "carter-number": "5",
      "complement-forte-code": "9-9",
      "documentation-link": null,
    },
    {
      "forte-code": "3-10",
      "pitch-classes": [0, 3, 6],
      name: "Diminished triad",
      "carter-number": "2",
      "complement-forte-code": "9-10",
      "documentation-link": null,
    },
    {
      "forte-code": "3-11",
      "pitch-classes": [0, 3, 7],
      name: "Tríada Menor / 6(no5)",
      "carter-number": null,
      "complement-forte-code": "9-11B",
      "documentation-link": null,
    },
  
    {
      "forte-code": "3-11B",
      "pitch-classes": [0, 4, 7],
      name: "Tríada Mayor / m6(no5)",
      "carter-number": null,
      "complement-forte-code": "9-11A",
      "documentation-link": null,
    },
    {
      "forte-code": "3-12",
      "pitch-classes": [0, 4, 8],
      name: "Augmented triad",
      "carter-number": "1",
      "complement-forte-code": "9-12",
      "documentation-link": null,
    },
    {
      "forte-code": "4-1",
      "pitch-classes": [0, 1, 2, 3],
      name: "Chromatic tetrachord",
      "carter-number": "1",
      "complement-forte-code": "8-1",
      "documentation-link": null,
    },
    {
      "forte-code": "4-2",
      "pitch-classes": [0, 1, 2, 4],
      name: "Major second tetracluster n.2",
      "carter-number": null,
        "complement-forte-code": "8-2B",
      "documentation-link": null,
    },
    {
      "forte-code": "4-2B",
      "pitch-classes": [0, 2, 3, 4],
        name: "Major second tetracluster n.1",
      "carter-number": null,
      "complement-forte-code": "8-2A",
      "documentation-link": null,
    },
    {
      "forte-code": "4-3",
      "pitch-classes": [0, 1, 3, 4],
      name: " mMaj9(no5) - Alternating tetrachord",
      "carter-number": "9",
      "complement-forte-code": "8-3",
      "documentation-link": null,
    },
    {
      "forte-code": "4-4",
      "pitch-classes": [0, 1, 2, 5],
      name: "Minor third tetracluster n.2",
      "carter-number": null,
        "complement-forte-code": "8-4B",
      "documentation-link": null,
    },
    
    {
      "forte-code": "4-4B",
      "pitch-classes": [0, 3, 4, 5],
        name: "Minor third tetracluster n.1",
      "carter-number": null,
      "complement-forte-code": "8-4A",
      "documentation-link": null,
    },
    {
      "forte-code": "4-5",
      "pitch-classes": [0, 1, 2, 6],
        name: "Major third tetracluster n.1 - 1 2b 5 7",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    {
      "forte-code": "4-5B",
      "pitch-classes": [0, 4, 5, 6],
        name: "Major third tetracluster n.2",
      "carter-number": null,
      "complement-forte-code": "8-5A",
      "documentation-link": null,
    },
    {
      "forte-code": "4-6",
      "pitch-classes": [0, 1, 2, 7],
      name: "Perfect fourth tetracord",
      "carter-number": "6",
      "complement-forte-code": "8-6",
      "documentation-link": null,
    },
    {
      "forte-code": "4-7",
      "pitch-classes": [0, 1, 4, 5],
      name: "Arabic tetracord - 2 2£ 3 7",
      "carter-number": "8",
      "complement-forte-code": "8-7",
      "documentation-link": null,
    },
    {
      "forte-code": "4-8",
      "pitch-classes": [0, 1, 5, 6],
      name: "Double fourth tetracord - 1 4# 5 7",
      "carter-number": "10",
      "complement-forte-code": "8-8",
      "documentation-link": null,
    },
    {
      "forte-code": "4-9",
      "pitch-classes": [0, 1, 6, 7],
      name: "Double tritone tetrachord",
      "carter-number": "2",
      "complement-forte-code": "8-9",
      "documentation-link": null,
    },
    {
      "forte-code": "4-10",
      "pitch-classes": [0, 2, 3, 5],
      name: "Minor or Dorian tetrachord",
      "carter-number": "3",
      "complement-forte-code": "8-10",
      "documentation-link": null,
    },
    {
      "forte-code": "4-11",
      "pitch-classes": [0, 1, 3, 5],
      name: "Maj9(no5) - Phrygian tetrachord",
      "carter-number": null,
      "complement-forte-code": "8-11B",
      "documentation-link": null,
    },
    
    {
      "forte-code": "4-11B",
      "pitch-classes": [0, 2, 4, 5],
      name: "Major or Ionian tetrachord - m9(no5)",
      "carter-number": null,
      "complement-forte-code": "8-11A",
      "documentation-link": null,
    },
    {
      "forte-code": "4-12",
      "pitch-classes": [0, 2, 3, 6],
      name: "Harmonic minor tetrachord - 7(9b) - mMaj6(no5)",
      "carter-number": null,
        "complement-forte-code": "8-12A",
      "documentation-link": null,
    },
    {
      "forte-code": "4-12B",
      "pitch-classes": [0, 3, 4, 6],
      name: "Major third diminished tetrachord - 1 2b 3b 6",
      "carter-number": null,
      "complement-forte-code": "8-12B",
      "documentation-link": null,
    },
    {
      "forte-code": "4-13",
      "pitch-classes": [0, 1, 3, 6],
      name: "Diminished 9b tetrachord",
      "carter-number": null,
        "complement-forte-code": "8-13B",
      "documentation-link": null,
    },
    {
      "forte-code": "4-13B",
      "pitch-classes": [0, 3, 5, 6],
        name: "Diminished perfect fourth tetrachord - 1 2 3b 6",
      "carter-number": null,
      "complement-forte-code": "8-13A",
      "documentation-link": null,
    },
    {
      "forte-code": "4-14",
      "pitch-classes": [0, 2, 3, 7],
      name: "Minor major second tetrachord - m9(no7) - Maj6(no5)",
      "carter-number": null,
        "complement-forte-code": "8-14A",
      "documentation-link": null,
    },

    {
      "forte-code": "4-14B",
      "pitch-classes": [0, 4, 5, 7],
      name: "Tetracordio Mayor cuarta justa",
      "carter-number": null,
      "complement-forte-code": "8-14B",
      "documentation-link": null,
    },
    
    {
      "forte-code": "4-15",
      "pitch-classes": [0, 1, 4, 6],
      name: "mMaj(11 no5) - All interval tetrachord no1",
      "carter-number": null,
        "complement-forte-code": "8-Z15B",
      "documentation-link": null,
    },
    {
      "forte-code": "4-15B",
      "pitch-classes": [0, 2, 5, 6],
      name: "7(9# no5) - All interval tetrachord no2",
      "carter-number": null,
        "complement-forte-code": "8-Z15A",
      "documentation-link": null,
    },
    {
      "forte-code": "4-16",
      "pitch-classes": [0, 1, 5, 7],
      name: "Maj7 4# - Minor second quartal tetrachord",
      "carter-number": null,
        "complement-forte-code": "8-16B",
      "documentation-link": null,
    },

    {
      "forte-code": "4-16B",
      "pitch-classes": [0, 2, 6, 7],
      name: "Tritone quartal tetrachord - 7(4 no5)",
      "carter-number": null,
      "complement-forte-code": "8-16A",
      "documentation-link": null,
    },
    {
      "forte-code": "4-17",
      "pitch-classes": [0, 3, 4, 7],
      name: "Major/minor tetrachord - Bitonal",
      "carter-number": "13",
      "complement-forte-code": "8-17",
      "documentation-link": null,
    },
    {
      "forte-code": "4-18",
      "pitch-classes": [0, 1, 4, 7],
      name: "Diminished major tetrachord - Dim Maj7",
      "carter-number": null,
        "complement-forte-code": "8-18B",
      "documentation-link": null,
    },
    {
      "forte-code": "4-18B",
      "pitch-classes": [0, 3, 6, 7],
        name: "Diminished minor tetrachord",
      "carter-number": null,
      "complement-forte-code": "8-18A",
      "documentation-link": null,
    },
    {
      "forte-code": "4-19",
      "pitch-classes": [0, 1, 4, 8],
      name: "Augmented minor tetrachord - mMaj7",
      "carter-number": null,
        "complement-forte-code": "8-19B",
      "documentation-link": null,
    },
    {
      "forte-code": "4-19B",
      "pitch-classes": [0, 3, 4, 8],
      name: "Augmented major tetrachord - Maj7+ ",
      "carter-number": null,
      "complement-forte-code": "8-19A",
      "documentation-link": null,
    },
    {
      "forte-code": "4-20",
      "pitch-classes": [0, 1, 5, 8],
      name: "Maj7 - Major seventh chord",
      "carter-number": "15",
      "complement-forte-code": "8-20",
      "documentation-link": null,
    },
    {
      "forte-code": "4-21",
      "pitch-classes": [0, 2, 4, 6],
      name: "Tonal or Lydian tetrachord - 7(9 no5)",
      "carter-number": "11",
      "complement-forte-code": "8-21",
      "documentation-link": null,
    },
    {
      "forte-code": "4-22",
      "pitch-classes": [0, 2, 4, 7],
      name: "Major tetrachord - 1 2 3 5 - Coltrane major",
      "carter-number": null,
        "complement-forte-code": "8-22B",
      "documentation-link": null,
    },
    {
      "forte-code": "4-22B",
      "pitch-classes": [0, 3, 5, 7],
      name: "Minor perfect fourth tetrachord - m11",
      "carter-number": null,
      "complement-forte-code": "8-22A",
      "documentation-link": null,
    },
    {
      "forte-code": "4-23",
      "pitch-classes": [0, 2, 5, 7],
      name: "Quartal tetrachord / m7(11 no5) - 7sus4",
      "carter-number": "4",
      "complement-forte-code": "8-23",
      "documentation-link": null,
    },
    {
      "forte-code": "4-24",
      "pitch-classes": [0, 2, 4, 8],
      name: "Augmented seventh chord - 7+",
      "carter-number": "16",
      "complement-forte-code": "8-24",
      "documentation-link": null,
    },
    {
      "forte-code": "4-25",
      "pitch-classes": [0, 2, 6, 8],
      name: "French sixth chord - [C7(no5) + F#7(no5)] - 7(5b)",
      "carter-number": "12",
      "complement-forte-code": "8-25",
      "documentation-link": null,
    },
    {
      "forte-code": "4-26",
      "pitch-classes": [0, 3, 5, 8],
      name: "m7 - Minor seventh chord",
      "carter-number": "14",
      "complement-forte-code": "8-26",
      "documentation-link": null,
    },
    {
      "forte-code": "4-27",
      "pitch-classes": [0, 2, 5, 8],
      name: "Half diminished chord - m7(5b) - m6",
      "carter-number": null,
        "complement-forte-code": "8-27B",
      "documentation-link": null,
    },
    {
      "forte-code": "4-27B",
      "pitch-classes": [0, 3, 6, 8],
      name: "Seventh chord - 7 - German sixth chord",
      "carter-number": null,
      "complement-forte-code": "8-27A",
      "documentation-link": null,
    },
    {
      "forte-code": "4-28",
      "pitch-classes": [0, 3, 6, 9],
      name: "Diminished seventh chord - dim7",
      "carter-number": "5",
      "complement-forte-code": "8-28",
      "documentation-link": null,
    },
    
    {
      "forte-code": "4-z29",
      "pitch-classes": [0, 1, 3, 7],
      name: "7(6 no5) - All intervals tetrachord n3 - Bm/C",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    {
      "forte-code": "4-Z29A",
      "pitch-classes": [0, 1, 3, 7],
      name: "Tetracordio todos los intervalos.3",
      "carter-number": "23",
      "complement-forte-code": "8-Z29B",
      "documentation-link": null,
    },
    {
      "forte-code": "4-Z29B",
      "pitch-classes": [0, 4, 6, 7],
      name: "Tetracordio todos los intervalos.4",
      "carter-number": "23",
      "complement-forte-code": "8-Z29A",
      "documentation-link": null,
    },
    {
      "forte-code": "5-1",
      "pitch-classes": [0, 1, 2, 3, 4],
      name: "Pentatónica Cromática",
      "carter-number": null,
      "complement-forte-code": "7-1",
      "documentation-link": null,
    },
    {
      "forte-code": "5-2",
      "pitch-classes": [0, 1, 2, 3, 5],
      name: "Pentacluster Segunda mayor.2",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    {
      "forte-code": "5-2A",
      "pitch-classes": [0, 1, 2, 3, 5],
      name: "Pentacluster Segunda mayor.2",
      "carter-number": null,
      "complement-forte-code": "7-2B",
      "documentation-link": null,
    },
    {
      "forte-code": "5-2B",
      "pitch-classes": [0, 2, 3, 4, 5],
      name: "Pentacluster Segunda mayor.1",
      "carter-number": null,
      "complement-forte-code": "7-2A",
      "documentation-link": null,
    },
    {
      "forte-code": "5-3",
      "pitch-classes": [0, 1, 2, 4, 5],
      name: "Pentatónica Mayor 9b",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    {
      "forte-code": "5-3A",
      "pitch-classes": [0, 1, 2, 4, 5],
      name: "Pentatónica Mayor 9b",
      "carter-number": null,
      "complement-forte-code": "7-3B",
      "documentation-link": null,
    },
    {
      "forte-code": "5-3B",
      "pitch-classes": [0, 1, 3, 4, 5],
      name: "Pentacluster Español",
      "carter-number": null,
      "complement-forte-code": "7-3A",
      "documentation-link": null,
    },
    {
      "forte-code": "5-4",
      "pitch-classes": [0, 1, 2, 3, 6],
      name: "Pentacluster Blues",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    {
      "forte-code": "5-4A",
      "pitch-classes": [0, 1, 2, 3, 6],
      name: "Pentacluster Blues",
      "carter-number": null,
      "complement-forte-code": "7-4B",
      "documentation-link": null,
    },
    {
      "forte-code": "5-4B",
      "pitch-classes": [0, 3, 4, 5, 6],
      name: "Pentacluster Tercera menor",
      "carter-number": null,
      "complement-forte-code": "7-4A",
      "documentation-link": null,
    },
    {
      "forte-code": "5-5",
      "pitch-classes": [0, 1, 2, 3, 7],
      name: "Pentacluster Tercera mayor.2",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    {
      "forte-code": "5-5A",
      "pitch-classes": [0, 1, 2, 3, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": "7-5B",
      "documentation-link": null,
    },
    {
      "forte-code": "5-5B",
      "pitch-classes": [0, 4, 5, 6, 7],
      name: "Pentacluster Tercera mayor.1",
      "carter-number": null,
      "complement-forte-code": "7-5A",
      "documentation-link": null,
    },
    {
      "forte-code": "5-6",
      "pitch-classes": [0, 1, 2, 5, 6],
      name: "Pentacluster Oriental.1",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    {
      "forte-code": "5-6A",
      "pitch-classes": [0, 1, 2, 5, 6],
      name: null,
      "carter-number": null,
      "complement-forte-code": "7-6B",
      "documentation-link": null,
    },
    {
      "forte-code": "5-6B",
      "pitch-classes": [0, 1, 4, 5, 6],
      name: "Pentacluster Oriental.2",
      "carter-number": null,
      "complement-forte-code": "7-6A",
      "documentation-link": null,
    },
    {
      "forte-code": "5-7",
      "pitch-classes": [0, 1, 2, 6, 7],
      name: "Pentacluster Doble.1",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    {
      "forte-code": "5-7A",
      "pitch-classes": [0, 1, 2, 6, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": "7-7B",
      "documentation-link": null,
    },
    {
      "forte-code": "5-7B",
      "pitch-classes": [0, 1, 5, 6, 7],
      name: "Pentacluster Doble.2",
      "carter-number": null,
      "complement-forte-code": "7-7A",
      "documentation-link": null,
    },
    {
      "forte-code": "5-8",
      "pitch-classes": [0, 2, 3, 4, 6],
      name: "Pentatónica Tritono-Simétrico",
      "carter-number": null,
      "complement-forte-code": "7-8",
      "documentation-link": null,
    },
    {
      "forte-code": "5-9",
      "pitch-classes": [0, 1, 2, 4, 6],
      name: "Pentatónica Tritono-expandido",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    {
      "forte-code": "5-9A",
      "pitch-classes": [0, 1, 2, 4, 6],
      name: null,
      "carter-number": null,
      "complement-forte-code": "7-9B",
      "documentation-link": null,
    },
    {
      "forte-code": "5-9B",
      "pitch-classes": [0, 2, 4, 5, 6],
      name: "Pentatónica Tritono-contraído",
      "carter-number": null,
      "complement-forte-code": "7-9A",
      "documentation-link": null,
    },
    {
      "forte-code": "5-10",
      "pitch-classes": [0, 1, 3, 4, 6],
      name: "Pentatónica Alternada.1",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    {
      "forte-code": "5-10A",
      "pitch-classes": [0, 1, 3, 4, 6],
      name: null,
      "carter-number": null,
      "complement-forte-code": "7-10B",
      "documentation-link": null,
    },
    {
      "forte-code": "5-10B",
      "pitch-classes": [0, 2, 3, 5, 6],
      name: "Pentatónica Alternada.2",
      "carter-number": null,
      "complement-forte-code": "7-10A",
      "documentation-link": null,
    },
    {
      "forte-code": "5-11",
      "pitch-classes": [0, 2, 3, 4, 7],
      name: "Pentatónica Cluster-central.1",
      "carter-number": null,
        "complement-forte-code": "7-11A",
      "documentation-link": null,
    },
    {
      "forte-code": "5-11B",
      "pitch-classes": [0, 3, 4, 5, 7],
      name: "Pentatónica Cluster-central.2",
      "carter-number": null,
      "complement-forte-code": "7-11B",
      "documentation-link": null,
    },
    {
      "forte-code": "5-12",
      "pitch-classes": [0, 1, 5, 6, 10],
      name: "Locrian pentatonic",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    {
      "forte-code": "5-13",
      "pitch-classes": [0, 1, 2, 4, 8],
      name: "Pentatónica Aumentada.1",
      "carter-number": null,
        "complement-forte-code": "7-13B",
      "documentation-link": null,
    },
    {
      "forte-code": "5-13B",
      "pitch-classes": [0, 2, 3, 4, 8],
      name: "Pentatónica Aumentada.2",
      "carter-number": null,
      "complement-forte-code": "7-13A",
      "documentation-link": null,
    },
    {
      "forte-code": "5-14",
      "pitch-classes": [0, 1, 2, 5, 7],
      name: "Pentatónica Doble-segunda triple-cuarta.1",
      "carter-number": null,
        "complement-forte-code": "7-14B",
      "documentation-link": null,
    },
    {
      "forte-code": "5-14B",
      "pitch-classes": [0, 2, 5, 6, 7],
      name: "Pentatónica Doble-segunda triple-cuarta.2",
      "carter-number": null,
      "complement-forte-code": "7-14A",
      "documentation-link": null,
    },
    {
      "forte-code": "5-15",
      "pitch-classes": [0, 1, 2, 6, 8],
      name: "Pentatónica Asimetrico",
      "carter-number": null,
      "complement-forte-code": "7-15",
      "documentation-link": null,
    },
    {
      "forte-code": "5-16",
      "pitch-classes": [0, 1, 3, 4, 7],
      name: "Pentatónica Mayor-menor-disminuido.1",
      "carter-number": null,
        "complement-forte-code": "7-16B",
      "documentation-link": null,
    },
    {
      "forte-code": "5-16B",
      "pitch-classes": [0, 3, 4, 6, 7],
      name: "Pentatónica Mayor-menor-disminuido.2",
      "carter-number": null,
      "complement-forte-code": "7-16A",
      "documentation-link": null,
    },
    {
      "forte-code": "5-19",
      "pitch-classes": [0, 1, 3, 6, 7],
      name: "Pentatónica Javanesa",
      "carter-number": null,
        "complement-forte-code": "7-19B",
      "documentation-link": null,
    },
    {
      "forte-code": "5-19B",
      "pitch-classes": [0, 1, 4, 6, 7],
      name: "Pentatónica Balinesa",
      "carter-number": null,
      "complement-forte-code": "7-19A",
      "documentation-link": null,
    },
    {
      "forte-code": "5-20",
      "pitch-classes": [0, 1, 5, 6, 8],
      name: "Pentatónica Pelog (12414)",
      "carter-number": null,
        "complement-forte-code": "7-20B",
      "documentation-link": null,
    },
    {
      "forte-code": "5-20B",
      "pitch-classes": [0, 2, 3, 7, 8],
      name: "Pentatónica Hirajoshi -21414-",
      "carter-number": null,
      "complement-forte-code": "7-20A",
      "documentation-link": null,
    },
    {
      "forte-code": "5-21",
      "pitch-classes": [0, 1, 4, 5, 8],
      name: "Pentatónica Siria (Raga Megharanji -13134-)",
      "carter-number": null,
        "complement-forte-code": "7-21B",
      "documentation-link": null,
    },
    {
      "forte-code": "5-21B",
      "pitch-classes": [0, 3, 4, 7, 8],
      name: "Pentatónica Libanesa",
      "carter-number": null,
      "complement-forte-code": "7-21A",
      "documentation-link": null,
    },
    {
      "forte-code": "5-22",
      "pitch-classes": [0, 1, 4, 7, 8],
      name: "Pentatónica Persa",
      "carter-number": null,
      "complement-forte-code": "7-22",
      "documentation-link": null,
    },
    {
      "forte-code": "5-23",
      "pitch-classes": [0, 2, 3, 5, 7],
      name: "Pentatónica menor",
      "carter-number": null,
        "complement-forte-code": "7-23B",
      "documentation-link": null,
    },
    {
      "forte-code": "5-23B",
      "pitch-classes": [0, 2, 4, 5, 7],
      name: "Pentatónica mayor",
      "carter-number": null,
      "complement-forte-code": "7-23A",
      "documentation-link": null,
    },
    {
      "forte-code": "5-24",
      "pitch-classes": [0, 1, 3, 5, 7],
      name: "Pentatónica Frigia",
      "carter-number": null,
        "complement-forte-code": "7-24B",
      "documentation-link": null,
    },
{
      "forte-code": "5-24B",
      "pitch-classes": [0, 2, 4, 6, 7],
      name: "Pentatónica Lidia",
      "carter-number": null,
      "complement-forte-code": "7-24A",
      "documentation-link": null,
    },
    {
      "forte-code": "5-25",
      "pitch-classes": [0, 2, 3, 5, 8],
      name: "Acode disminuido novena mayor",
      "carter-number": null,
        "complement-forte-code": "7-25B",
      "documentation-link": null,
    },
    {
      "forte-code": "5-25B",
      "pitch-classes": [0, 3, 5, 6, 8],
      name: "Acorde Menor 9b",
      "carter-number": null,
      "complement-forte-code": "7-25A",
      "documentation-link": null,
    },
    {
      "forte-code": "5-26",
      "pitch-classes": [0, 2, 4, 5, 8],
      name: "Acorde Disminuido 9#",
      "carter-number": null,
        "complement-forte-code": "7-26A",
      "documentation-link": null,
    },
    {
      "forte-code": "5-26B",
      "pitch-classes": [0, 3, 4, 6, 8],
      name: "Acorde Aumentado 9b",
      "carter-number": null,
      "complement-forte-code": "7-26B",
      "documentation-link": null,
    },
    {
      "forte-code": "5-27",
      "pitch-classes": [0, 1, 3, 5, 8],
      name: "Acorde Mayor",
      "carter-number": null,
        "complement-forte-code": "7-27B",
      "documentation-link": null,
    },
    {
      "forte-code": "5-27B",
      "pitch-classes": [0, 3, 5, 7, 8],
      name: "Acorde Menor",
      "carter-number": null,
      "complement-forte-code": "7-27A",
      "documentation-link": null,
    },
    {
      "forte-code": "5-28",
      "pitch-classes": [0, 2, 3, 6, 8],
      name: "Pentatónica Aumentada-sexta.1",
      "carter-number": null,
        "complement-forte-code": "7-28A",
      "documentation-link": null,
    },
    {
      "forte-code": "5-28B",
      "pitch-classes": [0, 2, 5, 6, 8],
      name: "Pentatónica Aumentada-sexta.2",
      "carter-number": null,
      "complement-forte-code": "7-28B",
      "documentation-link": null,
    },
    {
      "forte-code": "5-29",
      "pitch-classes": [0, 1, 3, 6, 8],
      name: "Pentatónica Kumoi.2",
      "carter-number": null,
        "complement-forte-code": "7-29B",
      "documentation-link": null,
    },
    {
      "forte-code": "5-29B",
      "pitch-classes": [0, 2, 5, 7, 8],
      name: "Pentatónica Kumoi.1",
      "carter-number": null,
      "complement-forte-code": "7-29A",
      "documentation-link": null,
    },
    {
      "forte-code": "5-30",
      "pitch-classes": [0, 1, 4, 6, 8],
      name: "Pentatónica Enigmatica .1",
      "carter-number": null,
        "complement-forte-code": "7-30B",
      "documentation-link": null,
    },
    {
      "forte-code": "5-30B",
      "pitch-classes": [0, 2, 4, 7, 8],
      name: "Pentatónica Enigmatica .2",
      "carter-number": null,
      "complement-forte-code": "7-30A",
      "documentation-link": null,
    },
    {
      "forte-code": "5-31",
      "pitch-classes": [0, 1, 3, 6, 9],
      name: "Acorde Disminuido 9b",
      "carter-number": null,
        "complement-forte-code": "7-31B",
      "documentation-link": null,
    },
    {
      "forte-code": "5-31B",
      "pitch-classes": [0, 2, 3, 6, 9],
      name: "Acorde Disminuido",
      "carter-number": null,
      "complement-forte-code": "7-31A",
      "documentation-link": null,
    },
    {
      "forte-code": "5-32",
      "pitch-classes": [0, 1, 4, 6, 9],
      name: "Pentatónica Napolitana.1",
      "carter-number": null,
        "complement-forte-code": "7-32B",
      "documentation-link": null,
    },
    {
      "forte-code": "5-32B",
      "pitch-classes": [0, 2, 5, 6, 9],
      name: "Pentatónica Napolitana.2",
      "carter-number": null,
      "complement-forte-code": "7-32A",
      "documentation-link": null,
    },
    {
      "forte-code": "5-33",
      "pitch-classes": [0, 2, 4, 6, 8],
      name: "Pentatónica Tonal",
      "carter-number": null,
      "complement-forte-code": "7-33",
      "documentation-link": null,
    },
    {
      "forte-code": "5-34",
      "pitch-classes": [0, 2, 4, 6, 9],
      name: "Pentatónica Prometeo",
      "carter-number": null,
      "complement-forte-code": "7-34",
      "documentation-link": null,
    },
    {
      "forte-code": "5-35",
      "pitch-classes": [0, 2, 4, 7, 9],
      name: "Pentatónica 'Tradicional'",
      "carter-number": null,
      "complement-forte-code": "7-35",
      "documentation-link": null,
    },
    {
      "forte-code": "5-35B",
      "pitch-classes": [0, 2, 4, 7, 9],
      name: "Traditional pentatonic",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    {
      "forte-code": "5-Z12",
      "pitch-classes": [0, 1, 3, 5, 6],
      name: "Pentatónica Simétrica Menor",
      "carter-number": null,
      "complement-forte-code": "7-Z12",
      "documentation-link": null,
    },
    {
      "forte-code": "5-Z17",
      "pitch-classes": [0, 1, 3, 4, 8],
      name: "Maj+(6) - Minor 9 chord",
      "carter-number": null,
      "complement-forte-code": "7-Z17",
      "documentation-link": null,
    },
    {
      "forte-code": "5-z18",
      "pitch-classes": [0, 1, 4, 5, 7],
      name: "Gypsy pentatonic n1",
      "carter-number": null,
        "complement-forte-code": "7-Z18B",
      "documentation-link": null,
    },
    {
      "forte-code": "5-Z18B",
      "pitch-classes": [0, 2, 3, 6, 7],
      name: "Gypsy pentatonic n2",
      "carter-number": null,
      "complement-forte-code": "7-Z18A",
      "documentation-link": null,
    },
    {
      "forte-code": "5-z36",
      "pitch-classes": [0, 1, 2, 4, 7],
      name: null,
      "carter-number": null,
        "complement-forte-code": "7-Z36B",
      "documentation-link": null,
    },
    {
      "forte-code": "5-Z36B",
      "pitch-classes": [0, 3, 5, 6, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": "7-Z36A",
      "documentation-link": null,
    },
    {
      "forte-code": "5-Z37",
      "pitch-classes": [0, 3, 4, 5, 8],
      name: "Pentatónica Simétrica Aumentada",
      "carter-number": null,
      "complement-forte-code": "7-Z37",
      "documentation-link": null,
    },
    {
      "forte-code": "5-z38",
      "pitch-classes": [0, 1, 2, 5, 8],
      name: "Pentatónica Simétrica Disminuida",
      "carter-number": null,
        "complement-forte-code": "7-Z38B",
      "documentation-link": null,
    },
    {
      "forte-code": "5-Z38B",
      "pitch-classes": [0, 3, 6, 7, 8],
      name: "Pentatónica Simétrica Disminuida.2",
      "carter-number": null,
      "complement-forte-code": "7-Z38A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-1",
      "pitch-classes": [0, 1, 2, 3, 4, 5],
      name: "Hexatónica Cromática",
      "carter-number": "4",
      "complement-forte-code": "6-1",
      "documentation-link": null,
    },
    {
      "forte-code": "6-2",
      "pitch-classes": [0, 1, 2, 3, 4, 6],
        name: "Hexatónica Cromática.2",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    {
      "forte-code": "6-2B",
      "pitch-classes": [0, 2, 3, 4, 5, 6],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-2A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-5",
      "pitch-classes": [0, 1, 2, 3, 6, 7],
        name: "Hexatónica Dórica.1",
      "carter-number": "5",
      "complement-forte-code": "6-5",
      "documentation-link": null,
    },
    {
      "forte-code": "6-5B",
      "pitch-classes": [0, 1, 4, 5, 6, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-5A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-7",
      "pitch-classes": [0, 1, 2, 6, 7, 8],
      name: "Messiaen modo",
      "carter-number": "7",
      "complement-forte-code": "6-7",
      "documentation-link": null,
    },
    {
      "forte-code": "6-8",
      "pitch-classes": [0, 2, 3, 4, 5, 7],
      name: null,
      "carter-number": "5",
      "complement-forte-code": "6-8",
      "documentation-link": null,
    },
    {
      "forte-code": "6-9",
      "pitch-classes": [0, 1, 2, 3, 5, 7],
        name: "Hexatónica Frigia.1",
      "carter-number": null,
        "complement-forte-code": "6-9B",
      "documentation-link": null,
    },
    {
      "forte-code": "6-9B",
      "pitch-classes": [0, 2, 4, 5, 6, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-9A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-14",
      "pitch-classes": [0, 1, 3, 4, 5, 8],
        name: "Hexatónica Aumentada.1A",
      "carter-number": null,
        "complement-forte-code": "6-14A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-14B",
      "pitch-classes": [0, 3, 4, 5, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-14B",
      "documentation-link": null,
    },
    {
      "forte-code": "6-15",
      "pitch-classes": [0, 1, 2, 4, 5, 8],
      name: null,
      "carter-number": null,
        "complement-forte-code": "6-15B",
      "documentation-link": null,
    },
    {
      "forte-code": "6-15B",
      "pitch-classes": [0, 3, 4, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-15A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-16",
      "pitch-classes": [0, 1, 4, 5, 6, 8],
      name: null,
      "carter-number": null,
        "complement-forte-code": "6-16B",
      "documentation-link": null,
    },
    {
      "forte-code": "6-16B",
      "pitch-classes": [0, 2, 3, 4, 7, 8],
      name: "Megha Raga",
      "carter-number": null,
      "complement-forte-code": "6-16A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-18",
      "pitch-classes": [0, 1, 2, 5, 7, 8],
      name: null,
      "carter-number": null,
        "complement-forte-code": "6-18B",
      "documentation-link": null,
    },
    {
      "forte-code": "6-18B",
      "pitch-classes": [0, 1, 3, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-18A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-20",
      "pitch-classes": [0, 1, 4, 5, 8, 9],
      name: "Escala Aumentada",
      "carter-number": "2",
      "complement-forte-code": "6-20",
      "documentation-link": null,
    },
    {
      "forte-code": "6-21",
      "pitch-classes": [0, 2, 3, 4, 6, 8],
        name: "Hexatónica Cromática.2A",
      "carter-number": null,
        "complement-forte-code": "6-21B",
      "documentation-link": null,
    },
    {
      "forte-code": "6-21B",
      "pitch-classes": [0, 2, 4, 5, 6, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-21A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-22",
      "pitch-classes": [0, 1, 2, 4, 6, 8],
      name: null,
      "carter-number": null,
        "complement-forte-code": "6-22B",
      "documentation-link": null,
    },
    {
      "forte-code": "6-22B",
      "pitch-classes": [0, 2, 4, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-21A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-27",
      "pitch-classes": [0, 1, 3, 4, 6, 9],
      name: null,
      "carter-number": null,
        "complement-forte-code": "6-27B",
      "documentation-link": null,
    },
    {
      "forte-code": "6-27B",
      "pitch-classes": [0, 2, 3, 5, 6, 9],
      name: "Hexatónica Pirámide",
      "carter-number": null,
      "complement-forte-code": "6-27A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-30",
      "pitch-classes": [0, 1, 3, 6, 7, 9],
      name: "Hexatónica Menor-bitonal",
        "carter-number": "15",
        "complement-forte-code": "6-30B",
      "documentation-link": null,
    },
    {
      "forte-code": "6-30B",
      "pitch-classes": [0, 2, 3, 6, 8, 9],
      name: "Hexacordio Mayor-bitonal",
      "carter-number": null,
      "complement-forte-code": "6-30A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-31",
      "pitch-classes": [0, 1, 4, 5, 7, 9],
      name: null,
      "carter-number": null,
        "complement-forte-code": "6-31B",
      "documentation-link": null,
    },
    {
      "forte-code": "6-31B",
      "pitch-classes": [0, 2, 4, 5, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-31A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-32",
      "pitch-classes": [0, 2, 4, 5, 7, 9],
      name: "Hexatónica mayor",
      "carter-number": "6",
      "complement-forte-code": "6-32",
      "documentation-link": null,
    },
    {
      "forte-code": "6-33",
      "pitch-classes": [0, 2, 3, 5, 7, 9],
      name: "Hexatónica Dórica no7",
      "carter-number": null,
        "complement-forte-code": "6-33B",
      "documentation-link": null,
    },
    {
      "forte-code": "6-33B",
      "pitch-classes": [0, 2, 4, 6, 7, 9],
      name: "Hexatónica Lidia no7",
      "carter-number": null,
      "complement-forte-code": "6-33A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-34",
      "pitch-classes": [0, 1, 3, 5, 7, 9],
      name: "Acorde Prometeo",
      "carter-number": null,
        "complement-forte-code": "6-34B",
      "documentation-link": null,
    },
    {
      "forte-code": "6-34B",
      "pitch-classes": [0, 2, 4, 6, 8, 9],
      name: "Hexatónica Armónica",
      "carter-number": null,
      "complement-forte-code": "6-34A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-35",
      "pitch-classes": [0, 2, 4, 6, 8, 10],
      name: "Escala Tonal",
      "carter-number": "1",
      "complement-forte-code": "6-35",
      "documentation-link": null,
    },
    {
      "forte-code": "6-z3",
      "pitch-classes": [0, 1, 2, 3, 5, 6],
      name: null,
      "carter-number": null,
        "complement-forte-code": "6-Z36B",
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z3B",
      "pitch-classes": [0, 1, 3, 4, 5, 6],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-Z36A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z4",
      "pitch-classes": [0, 1, 2, 4, 5, 6],
      name: null,
      "carter-number": "24",
      "complement-forte-code": "6-Z37",
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z6",
      "pitch-classes": [0, 1, 2, 5, 6, 7],
      name: "Double cluster Hexatonic",
      "carter-number": "33",
      "complement-forte-code": "6-Z38",
      "documentation-link": null,
    },
    {
      "forte-code": "6-z10",
      "pitch-classes": [0, 1, 3, 4, 5, 7],
      name: null,
      "carter-number": null,
        "complement-forte-code": "6-Z39A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z10B",
      "pitch-classes": [0, 2, 3, 4, 6, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-Z39B",
      "documentation-link": null,
    },
    {
      "forte-code": "6-z11",
      "pitch-classes": [0, 1, 2, 4, 5, 7],
      name: null,
      "carter-number": null,
        "complement-forte-code": "6-Z40B",
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z11B",
      "pitch-classes": [0, 2, 3, 5, 6, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-Z40A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-z12",
      "pitch-classes": [0, 1, 2, 4, 6, 7],
      name: null,
      "carter-number": null,
        "complement-forte-code": "6-Z41B",
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z12B",
      "pitch-classes": [0, 1, 3, 5, 6, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-Z41A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z13",
      "pitch-classes": [0, 1, 3, 4, 6, 7],
      name: "Alternated Hexatonic",
      "carter-number": "29",
      "complement-forte-code": "6-Z42",
      "documentation-link": null,
    },
    {
      "forte-code": "6-z17",
      "pitch-classes": [0, 1, 2, 4, 7, 8],
      name: "All intervals hexatonic",
      "carter-number": null,
        "complement-forte-code": "6-Z43B",
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z17B",
      "pitch-classes": [0, 1, 4, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-Z43A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-z19",
      "pitch-classes": [0, 1, 3, 4, 7, 8],
      name: "Pseudo Augmented minor - mMaj9(4#) - Lydian 3b(no6)",
      "carter-number": null,
        "complement-forte-code": "6-Z44B",
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z19B",
      "pitch-classes": [0, 1, 4, 5, 7, 8],
      name: "Maj7(2#4) - Lydian2# (no6)",
      "carter-number": null,
      "complement-forte-code": "6-Z44A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z23",
      "pitch-classes": [0, 2, 3, 5, 6, 8],
      name: "Super locrian Hexatonic",
      "carter-number": "27",
      "complement-forte-code": "6-Z45",
      "documentation-link": null,
    },
    {
      "forte-code": "6-z24",
      "pitch-classes": [0, 1, 3, 4, 6, 8],
      name: null,
      "carter-number": null,
        "complement-forte-code": "6-Z46B",
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z24B",
      "pitch-classes": [0, 2, 4, 5, 7, 8],
      name: "Melodic minor Hexatonic - mMaj9(6)",
      "carter-number": null,
      "complement-forte-code": "6-Z46A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-z25",
      "pitch-classes": [0, 1, 3, 5, 6, 8],
      name: "Locrian no7 Hexachord - Suddha Saveri raga -Ionian no6",
      "carter-number": null,
        "complement-forte-code": "6-Z47B",
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z25B",
      "pitch-classes": [0, 2, 3, 5, 7, 8],
      name: "minor Hexatonic - Dorian no4 - m9(6)",
      "carter-number": null,
      "complement-forte-code": "6-Z47A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z26",
      "pitch-classes": [0, 1, 3, 5, 7, 8],
      name: "Phrygian no7 hexatonic - Lydian no6 - Maj9(4#)",
      "carter-number": "26",
      "complement-forte-code": "6-Z48",
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z28",
      "pitch-classes": [0, 1, 3, 5, 6, 9],
      name: "Double Phrygian hexatonic",
      "carter-number": "21",
      "complement-forte-code": "6-Z49",
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z29",
      "pitch-classes": [0, 2, 3, 6, 7, 9],
      name: null,
      "carter-number": "32",
      "complement-forte-code": "6-Z50",
      "documentation-link": null,
    },
    {
      "forte-code": "6-z36",
      "pitch-classes": [0, 1, 2, 3, 4, 7],
      name: null,
      "carter-number": null,
        "complement-forte-code": "6-Z3B",
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z36B",
      "pitch-classes": [0, 3, 4, 5, 6, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-Z3A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z37",
      "pitch-classes": [0, 1, 2, 3, 4, 8],
      name: null,
      "carter-number": "23",
      "complement-forte-code": "6-Z4",
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z38",
      "pitch-classes": [0, 1, 2, 3, 7, 8],
      name: "Two quartal triads one semitone apart",
      "carter-number": "34",
      "complement-forte-code": "6-Z6",
      "documentation-link": null,
    },
    {
      "forte-code": "6-z39",
      "pitch-classes": [0, 2, 3, 4, 5, 8],
      name: null,
      "carter-number": null,
        "complement-forte-code": "6-Z10A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z39B",
      "pitch-classes": [0, 3, 4, 5, 6, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-Z10B",
      "documentation-link": null,
    },
    {
      "forte-code": "6-z40",
      "pitch-classes": [0, 1, 2, 3, 5, 8],
      name: null,
      "carter-number": null,
        "complement-forte-code": "6-Z11B",
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z40B",
      "pitch-classes": [0, 3, 5, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-Z11A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-z41",
      "pitch-classes": [0, 1, 2, 3, 6, 8],
      name: null,
      "carter-number": null,
        "complement-forte-code": "6-Z12B",
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z41B",
      "pitch-classes": [0, 2, 5, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-Z12A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z42",
      "pitch-classes": [0, 1, 2, 3, 6, 9],
      name: null,
      "carter-number": "30",
      "complement-forte-code": "6-Z13",
      "documentation-link": null,
    },
    {
      "forte-code": "6-z43",
      "pitch-classes": [0, 1, 2, 5, 6, 8],
      name: null,
      "carter-number": null,
        "complement-forte-code": "6-Z17B",
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z43B",
      "pitch-classes": [0, 2, 3, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-Z17A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-z44",
      "pitch-classes": [0, 1, 2, 5, 6, 9],
      name: "Schoemberg anagram hexatonic",
      "carter-number": null,
        "complement-forte-code": "6-Z19B",
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z44B",
      "pitch-classes": [0, 1, 4, 5, 6, 9],
      name: "Bauli Raga 133131",
      "carter-number": null,
      "complement-forte-code": "6-Z19A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z45",
      "pitch-classes": [0, 2, 3, 4, 6, 9],
      name: null,
      "carter-number": "28",
      "complement-forte-code": "6-Z23",
      "documentation-link": null,
    },
    {
      "forte-code": "6-z46",
      "pitch-classes": [0, 1, 2, 4, 6, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z46B",
      "pitch-classes": [0, 2, 4, 5, 6, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-Z24A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-z47",
      "pitch-classes": [0, 1, 2, 4, 7, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z47B",
      "pitch-classes": [0, 2, 3, 4, 7, 9],
      name: "Blues mode 1 321132",
      "carter-number": null,
      "complement-forte-code": "6-Z25A",
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z48",
      "pitch-classes": [0, 1, 2, 5, 7, 9],
      name: null,
      "carter-number": "25",
      "complement-forte-code": "6-Z26",
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z49",
      "pitch-classes": [0, 1, 3, 4, 7, 9],
      name: "Prometeus napolitan 132312",
      "carter-number": "22",
      "complement-forte-code": "6-Z28",
      "documentation-link": null,
    },
    {
      "forte-code": "6-Z50",
      "pitch-classes": [0, 1, 4, 6, 7, 9],
      name: "C + F#m",
      "carter-number": "31",
      "complement-forte-code": "6-Z29",
      "documentation-link": null,
    },
    {
      "forte-code": "7-1",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 6],
      name: "Heptatónica Cromática",
      "carter-number": "1",
      "complement-forte-code": "5-1",
      "documentation-link": null,
    },
    {
      "forte-code": "7-2",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    {
      "forte-code": "7-2B",
      "pitch-classes": [0, 2, 3, 4, 5, 6, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-2A",
      "documentation-link": null,
    },
    {
      "forte-code": "7-3",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    {
      "forte-code": "7-3B",
      "pitch-classes": [0, 3, 4, 5, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-3A",
      "documentation-link": null,
    },
    {
      "forte-code": "7-4",
      "pitch-classes": [0, 1, 2, 3, 4, 6, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    {
      "forte-code": "7-4B",
      "pitch-classes": [0, 1, 3, 4, 5, 6, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-4A",
      "documentation-link": null,
    },
    {
      "forte-code": "7-5",
      "pitch-classes": [0, 1, 2, 3, 5, 6, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    {
      "forte-code": "7-5B",
      "pitch-classes": [0, 1, 2, 4, 5, 6, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-5A",
      "documentation-link": null,
    },
    {
      "forte-code": "7-6",
      "pitch-classes": [0, 1, 2, 3, 4, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    {
      "forte-code": "7-6B",
      "pitch-classes": [0, 1, 4, 5, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-6A",
      "documentation-link": null,
    },
    {
      "forte-code": "7-7",
      "pitch-classes": [0, 1, 2, 3, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    {
      "forte-code": "7-7B",
      "pitch-classes": [0, 1, 2, 5, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-7A",
      "documentation-link": null,
    },
    {
      "forte-code": "7-8",
      "pitch-classes": [0, 2, 3, 4, 5, 6, 8],
      name: null,
      "carter-number": "2",
      "complement-forte-code": "5-8",
      "documentation-link": null,
    },
    {
      "forte-code": "7-9",
      "pitch-classes": [0, 1, 2, 3, 4, 6, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    {
      "forte-code": "7-9B",
      "pitch-classes": [0, 2, 4, 5, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-9A",
      "documentation-link": null,
    },
    {
      "forte-code": "7-10",
      "pitch-classes": [0, 1, 2, 3, 4, 6, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    {
      "forte-code": "7-10B",
      "pitch-classes": [0, 2, 3, 4, 5, 6, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-10A",
      "documentation-link": null,
    },
    {
      "forte-code": "7-11",
      "pitch-classes": [0, 1, 3, 4, 5, 6, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
   
    {
      "forte-code": "7-11B",
      "pitch-classes": [0, 2, 3, 4, 5, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-11B",
      "documentation-link": null,
    },
    {
      "forte-code": "7-13",
      "pitch-classes": [0, 1, 2, 4, 5, 6, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    
    {
      "forte-code": "7-13B",
      "pitch-classes": [0, 2, 3, 4, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-13A",
      "documentation-link": null,
    },
    {
      "forte-code": "7-14",
      "pitch-classes": [0, 1, 2, 3, 5, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    
    {
      "forte-code": "7-14B",
      "pitch-classes": [0, 1, 3, 5, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-14A",
      "documentation-link": null,
    },
    {
      "forte-code": "7-15",
      "pitch-classes": [0, 1, 2, 4, 6, 7, 8],
      name: null,
      "carter-number": "4",
      "complement-forte-code": "5-15",
      "documentation-link": null,
    },
    {
      "forte-code": "7-16",
      "pitch-classes": [0, 1, 2, 3, 5, 6, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    
    {
      "forte-code": "7-16B",
      "pitch-classes": [0, 1, 3, 4, 5, 6, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-16A",
      "documentation-link": null,
    },
    {
      "forte-code": "7-19",
      "pitch-classes": [0, 1, 2, 3, 6, 7, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
   
    {
      "forte-code": "7-19B",
      "pitch-classes": [0, 1, 2, 3, 6, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-19A",
      "documentation-link": null,
    },
    {
      "forte-code": "7-20",
      "pitch-classes": [0, 1, 2, 5, 6, 7, 9],
      name: "Frigia Cromática inversa (1123113)",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
  
    {
      "forte-code": "7-20B",
      "pitch-classes": [0, 2, 3, 4, 7, 8, 9],
      name: "Mixolidia cromática -1131132-",
      "carter-number": null,
      "complement-forte-code": "5-20A",
      "documentation-link": null,
    },
    {
      "forte-code": "7-21",
      "pitch-classes": [0, 1, 2, 4, 5, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },

    {
      "forte-code": "7-21B",
      "pitch-classes": [0, 1, 3, 4, 5, 8, 9],
      name: "Heptatónica Gypsy -1312113-",
      "carter-number": null,
      "complement-forte-code": "5-21A",
      "documentation-link": null,
    },
    {
      "forte-code": "7-22",
      "pitch-classes": [0, 1, 2, 5, 6, 8, 9],
      name: "Húngara Menor",
      "carter-number": "8",
      "complement-forte-code": "5-22",
      "documentation-link": null,
    },
    {
      "forte-code": "7-23",
      "pitch-classes": [0, 2, 3, 4, 5, 7, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },

    {
      "forte-code": "7-23B",
      "pitch-classes": [0, 2, 4, 5, 6, 7, 9],
      name: "Heptatónica Mayor + Tritono",
      "carter-number": null,
      "complement-forte-code": "5-23A",
      "documentation-link": null,
    },
    {
      "forte-code": "7-24",
      "pitch-classes": [0, 1, 2, 3, 5, 7, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },

    {
      "forte-code": "7-24B",
      "pitch-classes": [0, 2, 4, 6, 7, 8, 9],
      name: "Heptatónica Enigmática (1322211)",
      "carter-number": null,
      "complement-forte-code": "5-24A",
      "documentation-link": null,
    },
    {
      "forte-code": "7-25",
      "pitch-classes": [0, 2, 3, 4, 6, 7, 9],
      name: "Heptatónica Blues",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    
    {
      "forte-code": "7-25B",
      "pitch-classes": [0, 2, 3, 5, 6, 7, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-25A",
      "documentation-link": null,
    },
    {
      "forte-code": "7-26",
      "pitch-classes": [0, 1, 3, 4, 5, 7, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    {
      "forte-code": "7-26A",
      "pitch-classes": [0, 1, 3, 4, 5, 7, 9],
      name: null,
      "carter-number": "26",
      "complement-forte-code": "5-26A",
      "documentation-link": null,
    },
    {
      "forte-code": "7-26B",
      "pitch-classes": [0, 2, 4, 5, 6, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-26B",
      "documentation-link": null,
    },
    {
      "forte-code": "7-27",
      "pitch-classes": [0, 1, 2, 4, 5, 7, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },

    {
      "forte-code": "7-27B",
      "pitch-classes": [0, 2, 4, 5, 7, 8, 9],
      name: "Blues Modificada (2121132)",
      "carter-number": null,
      "complement-forte-code": "5-27A",
      "documentation-link": null,
    },
    {
      "forte-code": "7-28",
      "pitch-classes": [0, 1, 3, 5, 6, 7, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },

    {
      "forte-code": "7-28B",
      "pitch-classes": [0, 2, 3, 4, 6, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-28B",
      "documentation-link": null,
    },
    {
      "forte-code": "7-29",
      "pitch-classes": [0, 1, 2, 4, 6, 7, 9],
      name: "Locria",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
  
    {
      "forte-code": "7-29B",
      "pitch-classes": [0, 2, 3, 5, 7, 8, 9],
      name: "Jónica 5b",
      "carter-number": null,
      "complement-forte-code": "5-29A",
      "documentation-link": null,
    },
    {
      "forte-code": "7-30",
      "pitch-classes": [0, 1, 2, 4, 6, 8, 9],
      name: "Menor Napolitana",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
 
    {
      "forte-code": "7-30B",
      "pitch-classes": [0, 1, 3, 5, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-30A",
      "documentation-link": null,
    },
    {
      "forte-code": "7-31",
      "pitch-classes": [0, 1, 3, 4, 6, 7, 9],
      name: "Húngara Mayor (Heptatónica Alternada.1)",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
 
    {
      "forte-code": "7-31B",
      "pitch-classes": [0, 2, 3, 5, 6, 8, 9],
      name: "Heptatónica Alternada.2",
      "carter-number": null,
      "complement-forte-code": "5-31A",
      "documentation-link": null,
    },
    {
      "forte-code": "7-32",
      "pitch-classes": [0, 1, 3, 4, 6, 8, 9],
      name: "Menor armónica",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
 
    {
      "forte-code": "7-32B",
      "pitch-classes": [0, 1, 3, 5, 6, 8, 9],
      name: "Mayor armónica",
      "carter-number": null,
      "complement-forte-code": "5-32A",
      "documentation-link": null,
    },
    {
      "forte-code": "7-33",
      "pitch-classes": [0, 1, 2, 4, 6, 8, 10],
      name: "Napolitana Mayor -1222221-",
      "carter-number": "6",
      "complement-forte-code": "5-33",
      "documentation-link": null,
    },
    {
      "forte-code": "7-34",
      "pitch-classes": [0, 1, 3, 4, 6, 8, 10],
      name: "Menor Melódica",
      "carter-number": "9",
      "complement-forte-code": "5-34",
      "documentation-link": null,
    },
    {
      "forte-code": "7-35",
      "pitch-classes": [0, 1, 3, 5, 6, 8, 10],
      name: "Diatónica",
      "carter-number": "7",
      "complement-forte-code": "5-35",
      "documentation-link": null,
    },
    {
      "forte-code": "7-Z12",
      "pitch-classes": [0, 1, 2, 3, 4, 7, 9],
      name: "Afro american blues scale",
      "carter-number": "5",
      "complement-forte-code": "5-Z12",
      "documentation-link": null,
    },
    {
      "forte-code": "7-Z17",
      "pitch-classes": [0, 1, 2, 4, 5, 6, 9],
      name: null,
      "carter-number": "10",
      "complement-forte-code": "5-Z17",
      "documentation-link": null,
    },
    {
      "forte-code": "7-z18",
      "pitch-classes": [0, 1, 4, 5, 6, 7, 9],
      name: "Enigmatica menor",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
 
    {
      "forte-code": "7-Z18B",
      "pitch-classes": [0, 2, 3, 4, 5, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-Z18A",
      "documentation-link": null,
    },
    {
      "forte-code": "7-z36",
      "pitch-classes": [0, 1, 2, 3, 5, 6, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
   
    {
      "forte-code": "7-Z36B",
      "pitch-classes": [0, 2, 3, 5, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-Z36A",
      "documentation-link": null,
    },
    {
      "forte-code": "7-Z37",
      "pitch-classes": [0, 1, 3, 4, 5, 7, 8],
      name: null,
      "carter-number": "3",
      "complement-forte-code": "5-Z37",
      "documentation-link": null,
    },
    {
      "forte-code": "7-z38",
      "pitch-classes": [0, 1, 2, 4, 5, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
  
    {
      "forte-code": "7-Z38B",
      "pitch-classes": [0, 1, 3, 4, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-Z38A",
      "documentation-link": null,
    },
    {
      "forte-code": "8-1",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 6, 7],
      name: "Octatónica Cromática",
      "carter-number": null,
      "complement-forte-code": "4-1",
      "documentation-link": null,
    },
    {
      "forte-code": "8-2",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 6, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    
    {
      "forte-code": "8-2B",
      "pitch-classes": [0, 2, 3, 4, 5, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-2A",
      "documentation-link": null,
    },
    {
      "forte-code": "8-3",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 6, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-3",
      "documentation-link": null,
    },
    {
      "forte-code": "8-4",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
   
    {
      "forte-code": "8-4B",
      "pitch-classes": [0, 1, 3, 4, 5, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-4A",
      "documentation-link": null,
    },
    {
      "forte-code": "8-5",
      "pitch-classes": [0, 1, 2, 3, 4, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    
    {
      "forte-code": "8-5B",
      "pitch-classes": [0, 1, 2, 4, 5, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-5A",
      "documentation-link": null,
    },
    {
      "forte-code": "8-6",
      "pitch-classes": [0, 1, 2, 3, 5, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-6",
      "documentation-link": null,
    },
    {
      "forte-code": "8-7",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-7",
      "documentation-link": null,
    },
    {
      "forte-code": "8-8",
      "pitch-classes": [0, 1, 2, 3, 4, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-8",
      "documentation-link": null,
    },
    {
      "forte-code": "8-9",
      "pitch-classes": [0, 1, 2, 3, 6, 7, 8, 9],
      name: "Messiaen Modo 4 (11131113)",
      "carter-number": null,
      "complement-forte-code": "4-9",
      "documentation-link": null,
    },
    {
      "forte-code": "8-10",
      "pitch-classes": [0, 2, 3, 4, 5, 6, 7, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-10",
      "documentation-link": null,
    },
    {
      "forte-code": "8-11",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 7, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    
    {
      "forte-code": "8-11B",
      "pitch-classes": [0, 2, 4, 5, 6, 7, 8, 9],
      name: "Octatónica Blues.1",
      "carter-number": null,
      "complement-forte-code": "4-11A",
      "documentation-link": null,
    },
    {
      "forte-code": "8-12",
      "pitch-classes": [0, 1, 3, 4, 5, 6, 7, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
   
    {
      "forte-code": "8-12B",
      "pitch-classes": [0, 2, 3, 4, 5, 6, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-12B",
      "documentation-link": null,
    },
    {
      "forte-code": "8-13",
      "pitch-classes": [0, 1, 2, 3, 4, 6, 7, 9],
      name: "Octatónica Blues.2",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    
    {
      "forte-code": "8-13B",
      "pitch-classes": [0, 2, 3, 5, 6, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-13A",
      "documentation-link": null,
    },
    {
      "forte-code": "8-14",
      "pitch-classes": [0, 1, 2, 4, 5, 6, 7, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    
    {
      "forte-code": "8-14B",
      "pitch-classes": [0, 2, 3, 4, 5, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-14B",
      "documentation-link": null,
    },
    {
      "forte-code": "8-16",
      "pitch-classes": [0, 1, 2, 3, 5, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
   
    {
      "forte-code": "8-16B",
      "pitch-classes": [0, 1, 2, 4, 6, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-16A",
      "documentation-link": null,
    },
    {
      "forte-code": "8-17",
      "pitch-classes": [0, 1, 3, 4, 5, 6, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-17",
      "documentation-link": null,
    },
    {
      "forte-code": "8-18",
      "pitch-classes": [0, 1, 2, 3, 5, 6, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    
    {
      "forte-code": "8-18B",
      "pitch-classes": [0, 1, 3, 4, 6, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-18A",
      "documentation-link": null,
    },
    {
      "forte-code": "8-19",
      "pitch-classes": [0, 1, 2, 4, 5, 6, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
   
    {
      "forte-code": "8-19B",
      "pitch-classes": [0, 1, 3, 4, 5, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-19A",
      "documentation-link": null,
    },
    {
      "forte-code": "8-20",
      "pitch-classes": [0, 1, 2, 4, 5, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-20",
      "documentation-link": null,
    },
    {
      "forte-code": "8-21",
      "pitch-classes": [0, 1, 2, 3, 4, 6, 8, 10],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-21",
      "documentation-link": null,
    },
    {
      "forte-code": "8-22",
      "pitch-classes": [0, 1, 2, 3, 5, 6, 8, 10],
      name: "Jonica Bebop (2b-2)",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
   
    {
      "forte-code": "8-22B",
      "pitch-classes": [0, 1, 3, 4, 5, 6, 8, 10],
      name: "Escala Octatónica Española -12111222-",
      "carter-number": null,
      "complement-forte-code": "4-22A",
      "documentation-link": null,
    },
    {
      "forte-code": "8-23",
      "pitch-classes": [0, 1, 2, 3, 5, 7, 8, 10],
      name: "Mixolidia Bebop (7b-7)",
      "carter-number": null,
      "complement-forte-code": "4-23",
      "documentation-link": null,
    },
    {
      "forte-code": "8-24",
      "pitch-classes": [0, 1, 2, 4, 5, 6, 8, 10],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-24",
      "documentation-link": null,
    },
    {
      "forte-code": "8-25",
      "pitch-classes": [0, 1, 2, 4, 6, 7, 8, 10],
      name: "Messiaen Modo 6 -11221122-",
      "carter-number": null,
      "complement-forte-code": "4-25",
      "documentation-link": null,
    },
    {
      "forte-code": "8-26",
      "pitch-classes": [0, 1, 3, 4, 5, 7, 8, 10],
      name: "Frigia Española -12112122-",
      "carter-number": null,
      "complement-forte-code": "4-26",
      "documentation-link": null,
    },
    {
      "forte-code": "8-27",
      "pitch-classes": [0, 1, 2, 4, 5, 7, 8, 10],
      name: "Menor 6ta disminuida - Barry Harris",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
   
    {
      "forte-code": "8-27B",
      "pitch-classes": [0, 1, 3, 4, 6, 7, 8, 10],
      name: "Dominante disminuida - Barry Harris",
      "carter-number": null,
      "complement-forte-code": "4-27A",
      "documentation-link": null,
    },
    {
      "forte-code": "8-28",
      "pitch-classes": [0, 1, 3, 4, 6, 7, 9, 10],
      name: "Octatónica Disminuida",
      "carter-number": null,
      "complement-forte-code": "4-28",
      "documentation-link": null,
    },
    {
      "forte-code": "8-z15",
      "pitch-classes": [0, 1, 2, 3, 4, 6, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
  
    {
      "forte-code": "8-Z15B",
      "pitch-classes": [0, 1, 3, 5, 6, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-Z15A",
      "documentation-link": null,
    },
    {
      "forte-code": "8-z29",
      "pitch-classes": [0, 1, 2, 3, 5, 6, 7, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    
    {
      "forte-code": "8-Z29B",
      "pitch-classes": [0, 2, 3, 4, 6, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-Z29A",
      "documentation-link": null,
    },
    {
      "forte-code": "9-1",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 6, 7, 8],
      name: "Nonacordio Cromático",
      "carter-number": null,
      "complement-forte-code": "3-1",
      "documentation-link": null,
    },
    {
      "forte-code": "9-2",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 6, 7, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
   
    {
      "forte-code": "9-2B",
      "pitch-classes": [0, 2, 3, 4, 5, 6, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "3-2A",
      "documentation-link": null,
    },
    {
      "forte-code": "9-3",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 6, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    
    {
      "forte-code": "9-3B",
      "pitch-classes": [0, 1, 3, 4, 5, 6, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "3-3A",
      "documentation-link": null,
    },
    {
      "forte-code": "9-4",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    
    {
      "forte-code": "9-4B",
      "pitch-classes": [0, 1, 2, 4, 5, 6, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "3-4A",
      "documentation-link": null,
    },
    {
      "forte-code": "9-5",
      "pitch-classes": [0, 1, 2, 3, 4, 6, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
   
    {
      "forte-code": "9-5B",
      "pitch-classes": [0, 1, 2, 3, 5, 6, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "3-5A",
      "documentation-link": null,
    },
    {
      "forte-code": "9-6",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 6, 8, 10],
      name: null,
      "carter-number": null,
      "complement-forte-code": "3-6",
      "documentation-link": null,
    },
    {
      "forte-code": "9-7",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 7, 8, 10],
      name: "Nonatónica Blues",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    
    {
      "forte-code": "9-7B",
      "pitch-classes": [0, 1, 3, 4, 5, 6, 7, 8, 10],
      name: null,
      "carter-number": null,
      "complement-forte-code": "3-7A",
      "documentation-link": null,
    },
    {
      "forte-code": "9-8",
      "pitch-classes": [0, 1, 2, 3, 4, 6, 7, 8, 10],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    
    {
      "forte-code": "9-8B",
      "pitch-classes": [0, 1, 2, 4, 5, 6, 7, 8, 10],
      name: null,
      "carter-number": null,
      "complement-forte-code": "3-8A",
      "documentation-link": null,
    },
    {
      "forte-code": "9-9",
      "pitch-classes": [0, 1, 2, 3, 5, 6, 7, 8, 10],
      name: "Raga Ramdasi Malhar -211122111-",
      "carter-number": null,
      "complement-forte-code": "3-9",
      "documentation-link": null,
    },
    {
      "forte-code": "9-10",
      "pitch-classes": [0, 1, 2, 3, 4, 6, 7, 9, 10],
      name: null,
      "carter-number": null,
      "complement-forte-code": "3-10",
      "documentation-link": null,
    },
    {
      "forte-code": "9-11",
      "pitch-classes": [0, 1, 2, 3, 5, 6, 7, 9, 10],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
   
    {
      "forte-code": "9-11B",
      "pitch-classes": [0, 1, 2, 4, 5, 6, 7, 9, 10],
      name: "Nonacordio Disminuido",
      "carter-number": null,
      "complement-forte-code": "3-11A",
      "documentation-link": null,
    },
    {
      "forte-code": "9-12",
      "pitch-classes": [0, 1, 2, 4, 5, 6, 8, 9, 10],
      name: "Tcherepnin",
      "carter-number": null,
      "complement-forte-code": "3-12",
      "documentation-link": null,
    },
    {
      "forte-code": "10-1",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
      name: "Decatónica Cromática",
      "carter-number": null,
      "complement-forte-code": "2-1",
      "documentation-link": null,
    },
    {
      "forte-code": "10-2",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 6, 7, 8, 10],
      name: null,
      "carter-number": null,
      "complement-forte-code": "2-2",
      "documentation-link": null,
    },
    {
      "forte-code": "10-3",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 6, 7, 9, 10],
      name: null,
      "carter-number": null,
      "complement-forte-code": "2-3",
      "documentation-link": null,
    },
    {
      "forte-code": "10-4",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 6, 8, 9, 10],
      name: null,
      "carter-number": null,
      "complement-forte-code": "2-4",
      "documentation-link": null,
    },
    {
      "forte-code": "10-5",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 7, 8, 9, 10],
      name: "Mayor-Menor mixta",
      "carter-number": null,
      "complement-forte-code": "2-5",
      "documentation-link": null,
    },
    {
      "forte-code": "10-6",
      "pitch-classes": [0, 1, 2, 3, 4, 6, 7, 8, 9, 10],
      name: "Messiaen modo 7 -1111211112-",
      "carter-number": null,
      "complement-forte-code": "2-6",
      "documentation-link": null,
    },
    {
      "forte-code": "11-1",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      name: "Undecatónica -11111111111- AAAAA5",
      "carter-number": null,
      "complement-forte-code": "1-1",
      "documentation-link": null,
    },
    {
      "forte-code": "12-1",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
      name: "Escala Cromática",
      "carter-number": null,
      "complement-forte-code": "0-1",
      "documentation-link": null,
    },
    {
      "forte-code": "7-Z36",
      "pitch-classes": [0, 1, 2, 3, 5, 6, 8],
      name: "Heptatónica Z36",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },
    
    {
      "forte-code": "7-Z36B",
      "pitch-classes": [0, 2, 3, 5, 6, 7, 8],
      name: "Heptatónica Z36.2",
      "carter-number": null,
      "complement-forte-code": "5-Z36A",
      "documentation-link": null,
    },
    {
      "forte-code": "8-Z29",
      "pitch-classes": [0, 1, 2, 3, 5, 6, 7, 9],
      name: "Octatónica Z29",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
    },

    {
      "forte-code": "8-Z29B",
      "pitch-classes": [0, 2, 3, 4, 6, 7, 8, 9],
      name: "Octatónica Z29.2",
      "carter-number": null,
      "complement-forte-code": "4-Z29A",
      "documentation-link": null,
    },
  ],

  /**
   * Returns the chord with the given forte code from the `CHORDS.data` array.
   * @param {string} forteCode - The forte code of the chord to retrieve.
   * @returns {Chord | undefined} The chord with the given forte code, or undefined if no
   * chord exists with that forte code.
   */
  getByForteCode(forteCode) {
    for (let chord of this.data) {
      if (chord["forte-code"] === forteCode) {
        return chord;
      }
    }
  },

  /**
   * Returns the chord with the specified pitch classes from the `CHORDS.data` array.
   * @param {Array<number>} pitchClasses - An array of pitch classes to match.
   * @returns {Chord | undefined} The chord object if found, otherwise undefined.
   */
  getByPitchClasses(pitchClasses) {
    pitchClasses = pitchClasses.sort((a, b) => a - b);
    for (let chord of this.data) {
      chordClasses = chord["pitch-classes"].sort((a, b) => a - b);
      if (pitchClasses.length !== chordClasses.length) continue;
      for (let i = 0; i < pitchClasses.length; i++) {
        if (pitchClasses[i] !== chordClasses[i]) break;
        if (i === pitchClasses.length - 1) return chord;
      }
    }
  },

  /**
   * Returns all chords with the given cardinality from the `CHORDS.data` array.
   * @param {number} cardinality - The cardinality of the chords to retrieve.
   * @returns {Array<Chord>} An array of chord objects with the given cardinality.
   */
  getAllByCardinality(cardinality) {
    const chordsWithCardinality = [];
    for (let chord of this.data) {
      if (chord["pitch-classes"].length === cardinality)
        chordsWithCardinality.push(chord);
    }
    return chordsWithCardinality;
  },

  /**
   * Updates the documentation links for chords based on Google Drive file mapping.
   * @param {Object} fileMap - A mapping of forte-codes to Google Drive file IDs
   */
  updateDocumentationLinks(fileMap) {
    if (!fileMap || typeof fileMap !== "object") {
      console.error("Invalid file map provided");
      return;
    }

    for (let chord of this.data) {
      const forteCode = chord["forte-code"];
      if (fileMap[forteCode]) {
        chord[
          "documentation-link"
        ] = `https://drive.google.com/file/d/${fileMap[forteCode]}/view?usp=drive_link`;
      }
    }
  },
};
