/**
 * @typedef {Object} Chord
 * @property {string} forte-code - The forte code of the chord.
 * @property {Array.<Number>} pitch-classes - An array of pitch classes that the chord is comprised of.
 * @property {string} name - The name of the chord.
 * @property {string | null} carter-number - The Carter number of the chord.
 * @property {string | null} complement-forte-code - The forte code of the complement of the chord.
 * @property {string | null} documentation-link - A link to the documentation for the chord.
 */

const CHORDS = {
  /** @type {Chord[]} */
  data: [
    {
      "forte-code": "3-1",
      "pitch-classes": [0, 1, 2],
      name: "Chromatic tricord",
      "carter-number": "4",
      "complement-forte-code": "9-1",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "3-2",
      "pitch-classes": [0, 1, 3],
      name: "Phrygian triad",
      "carter-number": null,
      "complement-forte-code": "9-2B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "3-2B",
      "pitch-classes": [0, 2, 3],
      name: "Minor tricord",
      "carter-number": null,
      "complement-forte-code": "9-2",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "3-3",
      "pitch-classes": [0, 1, 4],
      name: "mMaj7(no5) - (Major/minor triad n1)",
      "carter-number": "11",
      "complement-forte-code": "9-3B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "3-3B",
      "pitch-classes": [0, 3, 4],
      name: "Major/minor triad n2",
      "carter-number": null,
      "complement-forte-code": "9-3",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "3-4",
      "pitch-classes": [0, 1, 5],
      name: "Maj7(no5) - incomplete Maj7 n1",
      "carter-number": null,
      "complement-forte-code": "9-4B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "3-4B",
      "pitch-classes": [0, 4, 5],
      name: "Maj7(no3) - incomplete Maj7 n2",
      "carter-number": null,
      "complement-forte-code": "9-4",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "3-5",
      "pitch-classes": [0, 1, 6],
      name: "Fourth/Tritone triad - Rite n1 - Lydian triad",
      "carter-number": null,
      "complement-forte-code": "9-5B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "3-5B",
      "pitch-classes": [0, 5, 6],
      name: "Tritone/Fourth triad - Rite n2 - Phrygian triad n2",
      "carter-number": null,
      "complement-forte-code": "9-5",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "3-6",
      "pitch-classes": [0, 2, 4],
      name: "Tonal triad",
      "carter-number": "3",
      "complement-forte-code": "9-6",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "3-7",
      "pitch-classes": [0, 2, 5],
      name: "m7(no5) - Incomplete minor seventh triad",
      "carter-number": null,
      "complement-forte-code": "9-7B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "3-7B",
      "pitch-classes": [0, 3, 5],
      name: "7(no3) - Incomplete dominant triad n1",
      "carter-number": null,
      "complement-forte-code": "9-7",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "3-8",
      "pitch-classes": [0, 2, 6],
      name: "7(no5) - Incomplete dominant triad n2 - Italian sixth",
      "carter-number": null,
      "complement-forte-code": "9-8B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "3-8B",
      "pitch-classes": [0, 4, 6],
      name: "5b triad - 1 3 5b ",
      "carter-number": null,
      "complement-forte-code": "9-8",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "3-9",
      "pitch-classes": [0, 2, 7],
      name: "Quartal triad",
      "carter-number": "5",
      "complement-forte-code": "9-9",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "3-10",
      "pitch-classes": [0, 3, 6],
      name: "Diminished triad",
      "carter-number": "2",
      "complement-forte-code": "9-10",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "3-11",
      "pitch-classes": [0, 3, 7],
      name: "Minor triad / 6(no5)",
      "carter-number": null,
      "complement-forte-code": "9-11B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "3-11B",
      "pitch-classes": [0, 4, 7],
      name: "Major triad / m6(no5)",
      "carter-number": null,
      "complement-forte-code": "9-11",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "3-12",
      "pitch-classes": [0, 4, 8],
      name: "Augmented triad",
      "carter-number": "1",
      "complement-forte-code": "9-12",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "4-1",
      "pitch-classes": [0, 1, 2, 3],
      name: "Chromatic tetrachord",
      "carter-number": "1",
      "complement-forte-code": "8-1",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "4-2",
      "pitch-classes": [0, 1, 2, 4],
      name: "Major second tetracluster n.2",
      "carter-number": null,
      "complement-forte-code": "8-2B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "4-2B",
      "pitch-classes": [0, 2, 3, 4],
      name: "Major second tetracluster n.1",
      "carter-number": null,
      "complement-forte-code": "8-2",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "4-3",
      "pitch-classes": [0, 1, 3, 4],
      name: " mMaj9(no5) - Alternating tetrachord",
      "carter-number": "9",
      "complement-forte-code": "8-3",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "4-4",
      "pitch-classes": [0, 1, 2, 5],
      name: "Minor third tetracluster n.2",
      "carter-number": null,
      "complement-forte-code": "8-4B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "4-4B",
      "pitch-classes": [0, 3, 4, 5],
      name: "Minor third tetracluster n.1",
      "carter-number": null,
      "complement-forte-code": "8-4",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "4-5",
      "pitch-classes": [0, 1, 2, 6],
      name: "Major third tetracluster n.1 - 1 2b 5 7",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "4-5B",
      "pitch-classes": [0, 4, 5, 6],
      name: "Major third tetracluster n.2",
      "carter-number": null,
      "complement-forte-code": "8-5",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "4-6",
      "pitch-classes": [0, 1, 2, 7],
      name: "Perfect fourth tetracord",
      "carter-number": "6",
      "complement-forte-code": "8-6",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "4-7",
      "pitch-classes": [0, 1, 4, 5],
      name: "Arabic tetracord - 2 2£ 3 7",
      "carter-number": "8",
      "complement-forte-code": "8-7",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "4-8",
      "pitch-classes": [0, 1, 5, 6],
      name: "Double fourth tetracord - 1 4# 5 7",
      "carter-number": "10",
      "complement-forte-code": "8-8",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "4-9",
      "pitch-classes": [0, 1, 6, 7],
      name: "Double tritone tetrachord",
      "carter-number": "2",
      "complement-forte-code": "8-9",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "4-10",
      "pitch-classes": [0, 2, 3, 5],
      name: "Minor or Dorian tetrachord",
      "carter-number": "3",
      "complement-forte-code": "8-10",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "4-11",
      "pitch-classes": [0, 1, 3, 5],
      name: "Maj9(no5) - Phrygian tetrachord",
      "carter-number": null,
      "complement-forte-code": "8-11B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "4-11B",
      "pitch-classes": [0, 2, 4, 5],
      name: "Major or Ionian tetrachord - m9(no5)",
      "carter-number": null,
      "complement-forte-code": "8-11",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "4-12",
      "pitch-classes": [0, 2, 3, 6],
      name: "Harmonic minor tetrachord - 7(9b) - mMaj6(no5)",
      "carter-number": null,
      "complement-forte-code": "8-12",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "4-12B",
      "pitch-classes": [0, 3, 4, 6],
      name: "Major third diminished tetrachord - 1 2b 3b 6",
      "carter-number": null,
      "complement-forte-code": "8-12B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "4-13",
      "pitch-classes": [0, 1, 3, 6],
      name: "Diminished 9b tetrachord",
      "carter-number": null,
      "complement-forte-code": "8-13B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "4-13B",
      "pitch-classes": [0, 3, 5, 6],
      name: "Diminished perfect fourth tetrachord - 1 2 3b 6",
      "carter-number": null,
      "complement-forte-code": "8-13",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "4-14",
      "pitch-classes": [0, 2, 3, 7],
      name: "Minor major second tetrachord - m9(no7) - Maj6(no5)",
      "carter-number": null,
      "complement-forte-code": "8-14",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "4-14B",
      "pitch-classes": [0, 4, 5, 7],
      name: "Major perfect fourth tetrachord ",
      "carter-number": null,
      "complement-forte-code": "8-14B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "4-15",
      "pitch-classes": [0, 1, 4, 6],
      name: "mMaj(11 no5) - All interval tetrachord no1",
      "carter-number": null,
      "complement-forte-code": "8-15B",
      "documentation-link": null,
      "*": false,
      Z: true,
    },
    {
      "forte-code": "4-15B",
      "pitch-classes": [0, 2, 5, 6],
      name: "7(9# no5) - All interval tetrachord no2",
      "carter-number": null,
      "complement-forte-code": "8-15",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "4-16",
      "pitch-classes": [0, 1, 5, 7],
      name: "Maj7 4# - Minor second quartal tetrachord",
      "carter-number": null,
      "complement-forte-code": "8-16B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "4-16B",
      "pitch-classes": [0, 2, 6, 7],
      name: "Tritone quartal tetrachord - 7(4 no5)",
      "carter-number": null,
      "complement-forte-code": "8-16",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "4-17",
      "pitch-classes": [0, 3, 4, 7],
      name: "Major/minor tetrachord - Bitonal",
      "carter-number": "13",
      "complement-forte-code": "8-17",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "4-18",
      "pitch-classes": [0, 1, 4, 7],
      name: "Diminished major tetrachord - Dim Maj7",
      "carter-number": null,
      "complement-forte-code": "8-18B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "4-18B",
      "pitch-classes": [0, 3, 6, 7],
      name: "Diminished minor tetrachord",
      "carter-number": null,
      "complement-forte-code": "8-18",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "4-19",
      "pitch-classes": [0, 1, 4, 8],
      name: "Augmented minor tetrachord - mMaj7",
      "carter-number": null,
      "complement-forte-code": "8-19B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "4-19B",
      "pitch-classes": [0, 3, 4, 8],
      name: "Augmented major tetrachord - Maj7+ ",
      "carter-number": null,
      "complement-forte-code": "8-19",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "4-20",
      "pitch-classes": [0, 1, 5, 8],
      name: "Maj7 - Major seventh chord",
      "carter-number": "15",
      "complement-forte-code": "8-20",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "4-21",
      "pitch-classes": [0, 2, 4, 6],
      name: "Tonal or Lydian tetrachord - 7(9 no5)",
      "carter-number": "11",
      "complement-forte-code": "8-21",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "4-22",
      "pitch-classes": [0, 2, 4, 7],
      name: "Major tetrachord - 1 2 3 5 - Coltrane major",
      "carter-number": null,
      "complement-forte-code": "8-22B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "4-22B",
      "pitch-classes": [0, 3, 5, 7],
      name: "Minor perfect fourth tetrachord - m11",
      "carter-number": null,
      "complement-forte-code": "8-22",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "4-23",
      "pitch-classes": [0, 2, 5, 7],
      name: "Quartal tetrachord / m7(11 no5) - 7sus4",
      "carter-number": "4",
      "complement-forte-code": "8-23",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "4-24",
      "pitch-classes": [0, 2, 4, 8],
      name: "Augmented seventh chord - 7+",
      "carter-number": "16",
      "complement-forte-code": "8-24",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "4-25",
      "pitch-classes": [0, 2, 6, 8],
      name: "French sixth chord - [C7(no5) + F#7(no5)] - 7(5b)",
      "carter-number": "12",
      "complement-forte-code": "8-25",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "4-26",
      "pitch-classes": [0, 3, 5, 8],
      name: "m7 - Minor seventh chord",
      "carter-number": "14",
      "complement-forte-code": "8-26",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "4-27",
      "pitch-classes": [0, 2, 5, 8],
      name: "Half diminished chord - m7(5b) - m6",
      "carter-number": null,
      "complement-forte-code": "8-27B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "4-27B",
      "pitch-classes": [0, 3, 6, 8],
      name: "Seventh chord - 7 - German sixth chord",
      "carter-number": null,
      "complement-forte-code": "8-27",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "4-28",
      "pitch-classes": [0, 3, 6, 9],
      name: "Diminished seventh chord - dim7",
      "carter-number": "5",
      "complement-forte-code": "8-28",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "4-29",
      "pitch-classes": [0, 1, 3, 7],
      name: "7(6 no5) - All intervals tetrachord n3 - Bm/C",
      "carter-number": null,
      "complement-forte-code": "8-29B",
      "documentation-link": null,
      "*": false,
      Z: true,
    },
    {
      "forte-code": "4-29B",
      "pitch-classes": [0, 4, 6, 7],
      name: " All intervals tetrachord n.4 - Major 4#",
      "carter-number": "23",
      "complement-forte-code": "8-29",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-1",
      "pitch-classes": [0, 1, 2, 3, 4],
      name: "Chromatic pentatonic",
      "carter-number": null,
      "complement-forte-code": "7-1",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "5-2",
      "pitch-classes": [0, 1, 2, 3, 5],
      name: "Major second pentacluster n.2",
      "carter-number": null,
      "complement-forte-code": "7-2B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-2B",
      "pitch-classes": [0, 2, 3, 4, 5],
      name: "Major second pentacluster n.1",
      "carter-number": null,
      "complement-forte-code": "7-2",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-3",
      "pitch-classes": [0, 1, 2, 4, 5],
      name: "Major 9b pentatonic",
      "carter-number": null,
      "complement-forte-code": "7-3B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-3B",
      "pitch-classes": [0, 1, 3, 4, 5],
      name: "Spanish pentacluster",
      "carter-number": null,
      "complement-forte-code": "7-3",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-4",
      "pitch-classes": [0, 1, 2, 3, 6],
      name: "Blues pentacluster ",
      "carter-number": null,
      "complement-forte-code": "7-4B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-4B",
      "pitch-classes": [0, 3, 4, 5, 6],
      name: "Minor third entacluster",
      "carter-number": null,
      "complement-forte-code": "7-4",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-5",
      "pitch-classes": [0, 1, 2, 3, 7],
      name: "Major second pentacluster n.2",
      "carter-number": null,
      "complement-forte-code": "7-5B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-5B",
      "pitch-classes": [0, 4, 5, 6, 7],
      name: "Major second pentacluster n.1",
      "carter-number": null,
      "complement-forte-code": "7-5",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-6",
      "pitch-classes": [0, 1, 2, 5, 6],
      name: " Oriental pentacluster n.1",
      "carter-number": null,
      "complement-forte-code": "7-6B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-6B",
      "pitch-classes": [0, 1, 4, 5, 6],
      name: " Oriental pentacluster n.2",
      "carter-number": null,
      "complement-forte-code": "7-6",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-7",
      "pitch-classes": [0, 1, 2, 6, 7],
      name: "Double Pentacluster n.1 -Raga Nabhomani",
      "carter-number": null,
      "complement-forte-code": "7-7B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-7B",
      "pitch-classes": [0, 1, 5, 6, 7],
      name: "Double Pentacluster n.2",
      "carter-number": null,
      "complement-forte-code": "7-7",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-8",
      "pitch-classes": [0, 2, 3, 4, 6],
      name: "Symetric tritone pentatonic - Mirror",
      "carter-number": null,
      "complement-forte-code": "7-8",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "5-9",
      "pitch-classes": [0, 1, 2, 4, 6],
      name: "Expanded tritone pentatonic",
      "carter-number": null,
      "complement-forte-code": "7-9B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-9B",
      "pitch-classes": [0, 2, 4, 5, 6],
      name: "Contracted tritone pentatonic",
      "carter-number": null,
      "complement-forte-code": "7-9",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-10",
      "pitch-classes": [0, 1, 3, 4, 6],
      name: "Alternated pentatonic n.1",
      "carter-number": null,
      "complement-forte-code": "7-10B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-10B",
      "pitch-classes": [0, 2, 3, 5, 6],
      name: "Alternated pentatonic n.2",
      "carter-number": null,
      "complement-forte-code": "7-10",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-11",
      "pitch-classes": [0, 2, 3, 4, 7],
      name: "Central-Cluster pentatonic n.1",
      "carter-number": null,
      "complement-forte-code": "7-11",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "5-11B",
      "pitch-classes": [0, 3, 4, 5, 7],
      name: "Central-Cluster pentatonic n.2",
      "carter-number": null,
      "complement-forte-code": "7-11B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-12",
      "pitch-classes": [0, 1, 3, 5, 6],
      name: "Locrian pentatonic",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": true,
      Z: true,
    },
    {
      "forte-code": "5-13",
      "pitch-classes": [0, 1, 2, 4, 8],
      name: "Augmented pentatonic n1",
      "carter-number": null,
      "complement-forte-code": "7-13B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-13B",
      "pitch-classes": [0, 2, 3, 4, 8],
      name: "Augmented pentatonic n2",
      "carter-number": null,
      "complement-forte-code": "7-13",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-14",
      "pitch-classes": [0, 1, 2, 5, 7],
      name: "Double second triple fourth pentatonic n.1",
      "carter-number": null,
      "complement-forte-code": "7-14B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-14B",
      "pitch-classes": [0, 2, 5, 6, 7],
      name: "Double second triple fourth pentatonic n.2",
      "carter-number": null,
      "complement-forte-code": "7-14",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-15",
      "pitch-classes": [0, 1, 2, 6, 8],
      name: "Asymetric pentatonic",
      "carter-number": null,
      "complement-forte-code": "7-15",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "5-16",
      "pitch-classes": [0, 1, 3, 4, 7],
      name: "Major/minor diminished pentatonic n.1",
      "carter-number": null,
      "complement-forte-code": "7-16B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-16B",
      "pitch-classes": [0, 3, 4, 6, 7],
      name: "Major/minor diminished pentatonic n.2",
      "carter-number": null,
      "complement-forte-code": "7-16",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-17",
      "pitch-classes": [0, 1, 3, 4, 8],
      name: "Maj+(6) - Minor 9 chord",
      "carter-number": null,
      "complement-forte-code": "7-17",
      "documentation-link": null,
      "*": true,
      Z: true,
    },
    {
      "forte-code": "5-18",
      "pitch-classes": [0, 1, 4, 5, 7],
      name: "Gypsy pentatonic n1",
      "carter-number": null,
      "complement-forte-code": "7-18B",
      "documentation-link": null,
      "*": false,
      Z: true,
    },
    {
      "forte-code": "5-18B",
      "pitch-classes": [0, 2, 3, 6, 7],
      name: "Gypsy pentatonic n2",
      "carter-number": null,
      "complement-forte-code": "7-18",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-19",
      "pitch-classes": [0, 1, 3, 6, 7],
      name: "Javanese Pentatonic",
      "carter-number": null,
      "complement-forte-code": "7-19B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-19B",
      "pitch-classes": [0, 1, 4, 6, 7],
      name: "Balinese Pentatonic",
      "carter-number": null,
      "complement-forte-code": "7-19",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-20",
      "pitch-classes": [0, 1, 5, 6, 8],
      name: "Pelog pentatonic",
      "carter-number": null,
      "complement-forte-code": "7-20B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-20B",
      "pitch-classes": [0, 2, 3, 7, 8],
      name: "Hirajoshi pentatonic",
      "carter-number": null,
      "complement-forte-code": "7-20",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-21",
      "pitch-classes": [0, 1, 4, 5, 8],
      name: "Sirian pentatonic",
      "carter-number": null,
      "complement-forte-code": "7-21B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-21B",
      "pitch-classes": [0, 3, 4, 7, 8],
      name: "Libanese pentatonic - Augmented minor chord",
      "carter-number": null,
      "complement-forte-code": "7-21",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-22",
      "pitch-classes": [0, 1, 4, 7, 8],
      name: " Persian pentatonic",
      "carter-number": null,
      "complement-forte-code": "7-22",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "5-23",
      "pitch-classes": [0, 2, 3, 5, 7],
      name: "Minor pentatonic",
      "carter-number": null,
      "complement-forte-code": "7-23B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-23B",
      "pitch-classes": [0, 2, 4, 5, 7],
      name: "Major pentatonic - m11(no5)",
      "carter-number": null,
      "complement-forte-code": "7-23",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-24",
      "pitch-classes": [0, 1, 3, 5, 7],
      name: "Phrygian pentatonic",
      "carter-number": null,
      "complement-forte-code": "7-24B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-24B",
      "pitch-classes": [0, 2, 4, 6, 7],
      name: "Lydian pentatonic",
      "carter-number": null,
      "complement-forte-code": "7-24",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-25",
      "pitch-classes": [0, 2, 3, 5, 8],
      name: "Diminished major ninth chord",
      "carter-number": null,
      "complement-forte-code": "7-25B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-25B",
      "pitch-classes": [0, 3, 5, 6, 8],
      name: "Diminished minor ninth chord",
      "carter-number": null,
      "complement-forte-code": "7-25",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-26",
      "pitch-classes": [0, 2, 4, 5, 8],
      name: "Diminished chord 9# - mMaj7(6)",
      "carter-number": null,
      "complement-forte-code": "7-26",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-26B",
      "pitch-classes": [0, 3, 4, 6, 8],
      name: "Augmented chord 9b",
      "carter-number": null,
      "complement-forte-code": "7-26B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-27",
      "pitch-classes": [0, 1, 3, 5, 8],
      name: "Major 9 chord - Maj9",
      "carter-number": null,
      "complement-forte-code": "7-27B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-27B",
      "pitch-classes": [0, 3, 5, 7, 8],
      name: "Minor 9 chord - m9 - Maj7(6)",
      "carter-number": null,
      "complement-forte-code": "7-27",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-28",
      "pitch-classes": [0, 2, 3, 6, 8],
      name: "Augmented sixth pentatonic n.1",
      "carter-number": null,
      "complement-forte-code": "7-28",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-28B",
      "pitch-classes": [0, 2, 5, 6, 8],
      name: "Augmented sixth pentatonic n.2",
      "carter-number": null,
      "complement-forte-code": "7-28B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-29",
      "pitch-classes": [0, 1, 3, 6, 8],
      name: "Kumoi pentatonic n.2",
      "carter-number": null,
      "complement-forte-code": "7-29B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-29B",
      "pitch-classes": [0, 2, 5, 7, 8],
      name: "Kumoi pentatonic n.1",
      "carter-number": null,
      "complement-forte-code": "7-29",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-30",
      "pitch-classes": [0, 1, 4, 6, 8],
      name: "Enigmatic pentatonic n.1",
      "carter-number": null,
      "complement-forte-code": "7-30B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-30B",
      "pitch-classes": [0, 2, 4, 7, 8],
      name: "Enigmatic pentatonic n.2 - Altered pentatonic",
      "carter-number": null,
      "complement-forte-code": "7-30",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-31",
      "pitch-classes": [0, 1, 3, 6, 9],
      name: "Diminished 9b chord",
      "carter-number": null,
      "complement-forte-code": "7-31B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-31B",
      "pitch-classes": [0, 2, 3, 6, 9],
      name: "Diminished 9 chord",
      "carter-number": null,
      "complement-forte-code": "7-31",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-32",
      "pitch-classes": [0, 1, 4, 6, 9],
      name: " Napolitan pentatonic n.1",
      "carter-number": null,
      "complement-forte-code": "7-32B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-32B",
      "pitch-classes": [0, 2, 5, 6, 9],
      name: " Napolitan pentatonic n.2",
      "carter-number": null,
      "complement-forte-code": "7-32",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-33",
      "pitch-classes": [0, 2, 4, 6, 8],
      name: "Tonal pentatonic",
      "carter-number": null,
      "complement-forte-code": "7-33",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "5-34",
      "pitch-classes": [0, 2, 4, 6, 9],
      name: "Prometeus pentatonic - m(4 6)",
      "carter-number": null,
      "complement-forte-code": "7-34",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "5-35",
      "pitch-classes": [0, 2, 4, 7, 9],
      name: "Traditional pentatonic",
      "carter-number": null,
      "complement-forte-code": "7-35",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "5-36",
      "pitch-classes": [0, 1, 2, 4, 7],
      name: "Major seventh pentacluster n.2",
      "carter-number": null,
      "complement-forte-code": "7-36B",
      "documentation-link": null,
      "*": false,
      Z: true,
    },
    {
      "forte-code": "5-36B",
      "pitch-classes": [0, 3, 5, 6, 7],
      name: "Major seventh pentacluster n.1",
      "carter-number": null,
      "complement-forte-code": "7-36",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "5-37",
      "pitch-classes": [0, 3, 4, 5, 8],
      name: "Central cluster pentatonic",
      "carter-number": null,
      "complement-forte-code": "7-37",
      "documentation-link": null,
      "*": true,
      Z: true,
    },
    {
      "forte-code": "5-38",
      "pitch-classes": [0, 1, 2, 5, 8],
      name: "Diminished pentacluster n.1",
      "carter-number": null,
      "complement-forte-code": "7-38B",
      "documentation-link": null,
      "*": false,
      Z: true,
    },
    {
      "forte-code": "5-38B",
      "pitch-classes": [0, 3, 6, 7, 8],
      name: "Diminished pentacluster n.2",
      "carter-number": null,
      "complement-forte-code": "7-38",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-1",
      "pitch-classes": [0, 1, 2, 3, 4, 5],
      name: "Chromatic hexatonic",
      "carter-number": "4",
      "complement-forte-code": "6-1",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "6-2",
      "pitch-classes": [0, 1, 2, 3, 4, 6],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-2B",
      "pitch-classes": [0, 2, 3, 4, 5, 6],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-2",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-3",
      "pitch-classes": [0, 1, 2, 3, 5, 6],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-36B",
      "documentation-link": null,
      "*": false,
      Z: true,
    },
    {
      "forte-code": "6-3B",
      "pitch-classes": [0, 1, 3, 4, 5, 6],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-36",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-4",
      "pitch-classes": [0, 1, 2, 4, 5, 6],
      name: null,
      "carter-number": "24",
      "complement-forte-code": "6-37",
      "documentation-link": null,
      "*": true,
      Z: true,
    },
    {
      "forte-code": "6-5",
      "pitch-classes": [0, 1, 2, 3, 6, 7],
      name: null,
      "carter-number": "5",
      "complement-forte-code": "6-5",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-5B",
      "pitch-classes": [0, 1, 4, 5, 6, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-5",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-6",
      "pitch-classes": [0, 1, 2, 5, 6, 7],
      name: "Double cluster Hexatonic",
      "carter-number": "33",
      "complement-forte-code": "6-38",
      "documentation-link": null,
      "*": true,
      Z: true,
    },
    {
      "forte-code": "6-7",
      "pitch-classes": [0, 1, 2, 6, 7, 8],
      name: "Messiaen mode 5 - [Cmaj7(no5) + F#Maj7(no5)]",
      "carter-number": "7",
      "complement-forte-code": "6-7",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "6-8",
      "pitch-classes": [0, 2, 3, 4, 5, 7],
      name: null,
      "carter-number": "5",
      "complement-forte-code": "6-8",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "6-9",
      "pitch-classes": [0, 1, 2, 3, 5, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-9B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-9B",
      "pitch-classes": [0, 2, 4, 5, 6, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-9",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-10",
      "pitch-classes": [0, 1, 3, 4, 5, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-39",
      "documentation-link": null,
      "*": false,
      Z: true,
    },
    {
      "forte-code": "6-10B",
      "pitch-classes": [0, 2, 3, 4, 6, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-39B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-11",
      "pitch-classes": [0, 1, 2, 4, 5, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-40B",
      "documentation-link": null,
      "*": false,
      Z: true,
    },
    {
      "forte-code": "6-11B",
      "pitch-classes": [0, 2, 3, 5, 6, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-40",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-12",
      "pitch-classes": [0, 1, 2, 4, 6, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-41B",
      "documentation-link": null,
      "*": false,
      Z: true,
    },
    {
      "forte-code": "6-12B",
      "pitch-classes": [0, 1, 3, 5, 6, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-41",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-13",
      "pitch-classes": [0, 1, 3, 4, 6, 7],
      name: "Alternated Hexatonic",
      "carter-number": "29",
      "complement-forte-code": "6-42",
      "documentation-link": null,
      "*": true,
      Z: true,
    },
    {
      "forte-code": "6-14",
      "pitch-classes": [0, 1, 3, 4, 5, 8],
      name: "Hexatónica Aumentada.1A",
      "carter-number": null,
      "complement-forte-code": "6-14",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-14B",
      "pitch-classes": [0, 3, 4, 5, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-14B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-15",
      "pitch-classes": [0, 1, 2, 4, 5, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-15B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-15B",
      "pitch-classes": [0, 3, 4, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-15",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-16",
      "pitch-classes": [0, 1, 4, 5, 6, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-16B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-16B",
      "pitch-classes": [0, 2, 3, 4, 7, 8],
      name: "Megha Raga",
      "carter-number": null,
      "complement-forte-code": "6-16",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-17",
      "pitch-classes": [0, 1, 2, 4, 7, 8],
      name: "All intervals hexatonic",
      "carter-number": null,
      "complement-forte-code": "6-43B",
      "documentation-link": null,
      "*": false,
      Z: true,
    },
    {
      "forte-code": "6-17B",
      "pitch-classes": [0, 1, 4, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-43",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-18",
      "pitch-classes": [0, 1, 2, 5, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-18B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-18B",
      "pitch-classes": [0, 1, 3, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-18",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-19",
      "pitch-classes": [0, 1, 3, 4, 7, 8],
      name: "Pseudo Augmented minor - mMaj9(4#) - Lydian 3b(no6)",
      "carter-number": null,
      "complement-forte-code": "6-44B",
      "documentation-link": null,
      "*": false,
      Z: true,
    },
    {
      "forte-code": "6-19B",
      "pitch-classes": [0, 1, 4, 5, 7, 8],
      name: "Maj7(2#4) - Lydian2# (no6)",
      "carter-number": null,
      "complement-forte-code": "6-44",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-20",
      "pitch-classes": [0, 1, 4, 5, 8, 9],
      name: "Augmented scale",
      "carter-number": "2",
      "complement-forte-code": "6-20",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "6-21",
      "pitch-classes": [0, 2, 3, 4, 6, 8],
      name: " Chromatic hexatonic n.2",
      "carter-number": null,
      "complement-forte-code": "6-21B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-21B",
      "pitch-classes": [0, 2, 4, 5, 6, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-21",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-22",
      "pitch-classes": [0, 1, 2, 4, 6, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-22B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-22B",
      "pitch-classes": [0, 2, 4, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-21",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-23",
      "pitch-classes": [0, 2, 3, 5, 6, 8],
      name: "Super locrian Hexatonic",
      "carter-number": "27",
      "complement-forte-code": "6-45",
      "documentation-link": null,
      "*": true,
      Z: true,
    },
    {
      "forte-code": "6-24",
      "pitch-classes": [0, 1, 3, 4, 6, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-46B",
      "documentation-link": null,
      "*": false,
      Z: true,
    },
    {
      "forte-code": "6-24B",
      "pitch-classes": [0, 2, 4, 5, 7, 8],
      name: "Melodic minor Hexatonic - mMaj9(6)",
      "carter-number": null,
      "complement-forte-code": "6-46",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-25",
      "pitch-classes": [0, 1, 3, 5, 6, 8],
      name: "Locrian no7 Hexachord - Suddha Saveri raga -Ionian no6",
      "carter-number": null,
      "complement-forte-code": "6-47B",
      "documentation-link": null,
      "*": true,
      Z: true,
    },
    {
      "forte-code": "6-25B",
      "pitch-classes": [0, 2, 3, 5, 7, 8],
      name: "minor Hexatonic - Dorian no4 - m9(6)",
      "carter-number": null,
      "complement-forte-code": "6-47",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-26",
      "pitch-classes": [0, 1, 3, 5, 7, 8],
      name: "Phrygian no7 hexatonic - Lydian no6 - Maj9(4#)",
      "carter-number": "26",
      "complement-forte-code": "6-48",
      "documentation-link": null,
      "*": true,
      Z: true,
    },
    {
      "forte-code": "6-27",
      "pitch-classes": [0, 1, 3, 4, 6, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-27B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-27B",
      "pitch-classes": [0, 2, 3, 5, 6, 9],
      name: "Pyramid hexatonic",
      "carter-number": null,
      "complement-forte-code": "6-27",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-28",
      "pitch-classes": [0, 1, 3, 5, 6, 9],
      name: "Double Phrygian hexatonic",
      "carter-number": "21",
      "complement-forte-code": "6-49",
      "documentation-link": null,
      "*": true,
      Z: true,
    },
    {
      "forte-code": "6-29",
      "pitch-classes": [0, 2, 3, 6, 7, 9],
      name: null,
      "carter-number": "32",
      "complement-forte-code": "6-50",
      "documentation-link": null,
      "*": true,
      Z: true,
    },
    {
      "forte-code": "6-30",
      "pitch-classes": [0, 1, 3, 6, 7, 9],
      name: "Minor bitonal hexatonic",
      "carter-number": "15",
      "complement-forte-code": "6-30B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-30B",
      "pitch-classes": [0, 2, 3, 6, 8, 9],
        name: "Major bitonal hexatonic",
      "carter-number": null,
      "complement-forte-code": "6-30",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-31",
      "pitch-classes": [0, 1, 4, 5, 7, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-31B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-31B",
      "pitch-classes": [0, 2, 4, 5, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-31",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-32",
      "pitch-classes": [0, 2, 4, 5, 7, 9],
      name: "Major hexatonic",
      "carter-number": "6",
      "complement-forte-code": "6-32",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "6-33",
      "pitch-classes": [0, 2, 3, 5, 7, 9],
      name: "Dorian no7 hexatonic",
      "carter-number": null,
      "complement-forte-code": "6-33B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-33B",
      "pitch-classes": [0, 2, 4, 6, 7, 9],
        name: "Lydian no7 hexatonic",
      "carter-number": null,
      "complement-forte-code": "6-33",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-34",
      "pitch-classes": [0, 1, 3, 5, 7, 9],
      name: "Prometeus chord",
      "carter-number": null,
      "complement-forte-code": "6-34B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-34B",
      "pitch-classes": [0, 2, 4, 6, 8, 9],
      name: "Harmonic hexatonic",
      "carter-number": null,
      "complement-forte-code": "6-34",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-35",
      "pitch-classes": [0, 2, 4, 6, 8, 10],
      name: "Tonal scale",
      "carter-number": "1",
      "complement-forte-code": "6-35",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "6-36",
      "pitch-classes": [0, 1, 2, 3, 4, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-3B",
      "documentation-link": null,
      "*": false,
      Z: true,
    },
    {
      "forte-code": "6-36B",
      "pitch-classes": [0, 3, 4, 5, 6, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-3",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-37",
      "pitch-classes": [0, 1, 2, 3, 4, 8],
      name: null,
      "carter-number": "23",
      "complement-forte-code": "6-4",
      "documentation-link": null,
      "*": true,
      Z: true,
    },
    {
      "forte-code": "6-38",
      "pitch-classes": [0, 1, 2, 3, 7, 8],
      name: "Two quartal triads one semitone apart",
      "carter-number": "34",
      "complement-forte-code": "6-6",
      "documentation-link": null,
      "*": true,
      Z: true,
    },
    {
      "forte-code": "6-39",
      "pitch-classes": [0, 2, 3, 4, 5, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-10",
      "documentation-link": null,
      "*": false,
      Z: true,
    },
    {
      "forte-code": "6-39B",
      "pitch-classes": [0, 3, 4, 5, 6, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-10B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-40",
      "pitch-classes": [0, 1, 2, 3, 5, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-11B",
      "documentation-link": null,
      "*": false,
      Z: true,
    },
    {
      "forte-code": "6-40B",
      "pitch-classes": [0, 3, 5, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-11",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-41",
      "pitch-classes": [0, 1, 2, 3, 6, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-12B",
      "documentation-link": null,
      "*": false,
      Z: true,
    },
    {
      "forte-code": "6-41B",
      "pitch-classes": [0, 2, 5, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-12",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-42",
      "pitch-classes": [0, 1, 2, 3, 6, 9],
      name: null,
      "carter-number": "30",
      "complement-forte-code": "6-13",
      "documentation-link": null,
      "*": true,
      Z: true,
    },
    {
      "forte-code": "6-43",
      "pitch-classes": [0, 1, 2, 5, 6, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-17B",
      "documentation-link": null,
      "*": false,
      Z: true,
    },
    {
      "forte-code": "6-43B",
      "pitch-classes": [0, 2, 3, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-17",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-44",
      "pitch-classes": [0, 1, 2, 5, 6, 9],
      name: "Schoemberg anagram hexatonic",
      "carter-number": null,
      "complement-forte-code": "6-19B",
      "documentation-link": null,
      "*": false,
      Z: true,
    },
    {
      "forte-code": "6-44B",
      "pitch-classes": [0, 1, 4, 5, 6, 9],
      name: "Bauli Raga 133131",
      "carter-number": null,
      "complement-forte-code": "6-19",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-45",
      "pitch-classes": [0, 2, 3, 4, 6, 9],
      name: null,
      "carter-number": "28",
      "complement-forte-code": "6-23",
      "documentation-link": null,
      "*": true,
      Z: true,
    },
    {
      "forte-code": "6-46",
      "pitch-classes": [0, 1, 2, 4, 6, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: true,
    },
    {
      "forte-code": "6-46B",
      "pitch-classes": [0, 2, 4, 5, 6, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "6-24",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-47",
      "pitch-classes": [0, 1, 2, 4, 7, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: true,
    },
    {
      "forte-code": "6-47B",
      "pitch-classes": [0, 2, 3, 4, 7, 9],
      name: "Blues mode 1 321132",
      "carter-number": null,
      "complement-forte-code": "6-25",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "6-48",
      "pitch-classes": [0, 1, 2, 5, 7, 9],
      name: null,
      "carter-number": "25",
      "complement-forte-code": "6-26",
      "documentation-link": null,
      "*": true,
      Z: true,
    },
    {
      "forte-code": "6-49",
      "pitch-classes": [0, 1, 3, 4, 7, 9],
      name: "Prometeus napolitan 132312",
      "carter-number": "22",
      "complement-forte-code": "6-28",
      "documentation-link": null,
      "*": true,
      Z: true,
    },
    {
      "forte-code": "6-50",
      "pitch-classes": [0, 1, 4, 6, 7, 9],
      name: "C + F#m",
      "carter-number": "31",
      "complement-forte-code": "6-29",
      "documentation-link": null,
      "*": true,
      Z: true,
    },
    {
      "forte-code": "7-1",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 6],
      name: "Cromatic heptatonic",
      "carter-number": "1",
      "complement-forte-code": "5-1",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "7-2",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-2B",
      "pitch-classes": [0, 2, 3, 4, 5, 6, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-2",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-3",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-3B",
      "pitch-classes": [0, 3, 4, 5, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-3",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-4",
      "pitch-classes": [0, 1, 2, 3, 4, 6, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-4B",
      "pitch-classes": [0, 1, 3, 4, 5, 6, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-4",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-5",
      "pitch-classes": [0, 1, 2, 3, 5, 6, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-5B",
      "pitch-classes": [0, 1, 2, 4, 5, 6, 7],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-5",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-6",
      "pitch-classes": [0, 1, 2, 3, 4, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-6B",
      "pitch-classes": [0, 1, 4, 5, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-6",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-7",
      "pitch-classes": [0, 1, 2, 3, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-7B",
      "pitch-classes": [0, 1, 2, 5, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-7",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-8",
      "pitch-classes": [0, 2, 3, 4, 5, 6, 8],
      name: null,
      "carter-number": "2",
      "complement-forte-code": "5-8",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "7-9",
      "pitch-classes": [0, 1, 2, 3, 4, 6, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-9B",
      "pitch-classes": [0, 2, 4, 5, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-9",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-10",
      "pitch-classes": [0, 1, 2, 3, 4, 6, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-10B",
      "pitch-classes": [0, 2, 3, 4, 5, 6, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-10",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-11",
      "pitch-classes": [0, 1, 3, 4, 5, 6, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-11B",
      "pitch-classes": [0, 2, 3, 4, 5, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-11B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-12",
      "pitch-classes": [0, 1, 2, 3, 4, 7, 9],
      name: "Afro american blues scale",
      "carter-number": "5",
      "complement-forte-code": "5-12",
      "documentation-link": null,
      "*": true,
      Z: true,
    },
    {
      "forte-code": "7-13",
      "pitch-classes": [0, 1, 2, 4, 5, 6, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-13B",
      "pitch-classes": [0, 2, 3, 4, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-13",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-14",
      "pitch-classes": [0, 1, 2, 3, 5, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-14B",
      "pitch-classes": [0, 1, 3, 5, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-14",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-15",
      "pitch-classes": [0, 1, 2, 4, 6, 7, 8],
      name: null,
      "carter-number": "4",
      "complement-forte-code": "5-15",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "7-16",
      "pitch-classes": [0, 1, 2, 3, 5, 6, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-16B",
      "pitch-classes": [0, 1, 3, 4, 5, 6, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-16",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-17",
      "pitch-classes": [0, 1, 2, 4, 5, 6, 9],
      name: null,
      "carter-number": "10",
      "complement-forte-code": "5-17",
      "documentation-link": null,
      "*": true,
      Z: true,
    },
    {
      "forte-code": "7-18",
      "pitch-classes": [0, 1, 4, 5, 6, 7, 9],
      name: "Enigmatica menor",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: true,
    },
    {
      "forte-code": "7-18B",
      "pitch-classes": [0, 2, 3, 4, 5, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-18",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-19",
      "pitch-classes": [0, 1, 2, 3, 6, 7, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-19B",
      "pitch-classes": [0, 1, 2, 3, 6, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-19",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-20",
      "pitch-classes": [0, 1, 2, 5, 6, 7, 9],
      name: "Inverse Chromatic Phrygian",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-20B",
      "pitch-classes": [0, 2, 3, 4, 7, 8, 9],
      name: "Chromatic mixolydian",
      "carter-number": null,
      "complement-forte-code": "5-20",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-21",
      "pitch-classes": [0, 1, 2, 4, 5, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-21B",
      "pitch-classes": [0, 1, 3, 4, 5, 8, 9],
      name: "Gypsy Heptatonic",
      "carter-number": null,
      "complement-forte-code": "5-21",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-22",
      "pitch-classes": [0, 1, 2, 5, 6, 8, 9],
      name: "Hungary minor",
      "carter-number": "8",
      "complement-forte-code": "5-22",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "7-23",
      "pitch-classes": [0, 2, 3, 4, 5, 7, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-23B",
      "pitch-classes": [0, 2, 4, 5, 6, 7, 9],
      name: "Major + tritone heptatonic",
      "carter-number": null,
      "complement-forte-code": "5-23",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-24",
      "pitch-classes": [0, 1, 2, 3, 5, 7, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-24B",
      "pitch-classes": [0, 2, 4, 6, 7, 8, 9],
      name: "Enigmatic heptatonic",
      "carter-number": null,
      "complement-forte-code": "5-24",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-25",
      "pitch-classes": [0, 2, 3, 4, 6, 7, 9],
      name: "Blues heptatonic",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-25B",
      "pitch-classes": [0, 2, 3, 5, 6, 7, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-25",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-26",
      "pitch-classes": [0, 1, 3, 4, 5, 7, 9],
      name: null,
      "carter-number": "26",
      "complement-forte-code": "5-26",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-26B",
      "pitch-classes": [0, 2, 4, 5, 6, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-26B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-27",
      "pitch-classes": [0, 1, 2, 4, 5, 7, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-27B",
      "pitch-classes": [0, 2, 4, 5, 7, 8, 9],
      name: "Blues Modified",
      "carter-number": null,
      "complement-forte-code": "5-27",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-28",
      "pitch-classes": [0, 1, 3, 5, 6, 7, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-28B",
      "pitch-classes": [0, 2, 3, 4, 6, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-28B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-29",
      "pitch-classes": [0, 1, 2, 4, 6, 7, 9],
      name: "Locrian natural seventh",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-29B",
      "pitch-classes": [0, 2, 3, 5, 7, 8, 9],
      name: "Ionian 5b",
      "carter-number": null,
      "complement-forte-code": "5-29",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-30",
      "pitch-classes": [0, 1, 2, 4, 6, 8, 9],
      name: "Napolitan minor heptatonic",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-30B",
      "pitch-classes": [0, 1, 3, 5, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-30",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-31",
      "pitch-classes": [0, 1, 3, 4, 6, 7, 9],
      name: "Hungary major - Alternated heptatonic.1",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-31B",
      "pitch-classes": [0, 2, 3, 5, 6, 8, 9],
      name: "Alternated heptatonic.2",
      "carter-number": null,
      "complement-forte-code": "5-31",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-32",
      "pitch-classes": [0, 1, 3, 4, 6, 8, 9],
      name: "Harmonic minor heptatonic",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-32B",
      "pitch-classes": [0, 1, 3, 5, 6, 8, 9],
      name: "Harmonic major heptatonic",
      "carter-number": null,
      "complement-forte-code": "5-32",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-33",
      "pitch-classes": [0, 1, 2, 4, 6, 8, 10],
      name: "Napolitan major - Leading tone heptatonic",
      "carter-number": "6",
      "complement-forte-code": "5-33",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "7-34",
      "pitch-classes": [0, 1, 3, 4, 6, 8, 10],
      name: "Melodic minor heptatonic",
      "carter-number": "9",
      "complement-forte-code": "5-34",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "7-35",
      "pitch-classes": [0, 1, 3, 5, 6, 8, 10],
      name: "Diatonic heptatonic",
      "carter-number": "7",
      "complement-forte-code": "5-35",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "7-36",
      "pitch-classes": [0, 1, 2, 3, 5, 6, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: true,
    },
    {
      "forte-code": "7-36B",
      "pitch-classes": [0, 2, 3, 5, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-36",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "7-37",
      "pitch-classes": [0, 1, 3, 4, 5, 7, 8],
      name: null,
      "carter-number": "3",
      "complement-forte-code": "5-37",
      "documentation-link": null,
      "*": true,
      Z: true,
    },
    {
      "forte-code": "7-38",
      "pitch-classes": [0, 1, 2, 4, 5, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: true,
    },
    {
      "forte-code": "7-38B",
      "pitch-classes": [0, 1, 3, 4, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "5-38",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "8-1",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 6, 7],
      name: "Chromatic octatonic",
      "carter-number": null,
      "complement-forte-code": "4-1",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "8-2",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 6, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "8-2B",
      "pitch-classes": [0, 2, 3, 4, 5, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-2",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "8-3",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 6, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-3",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "8-4",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "8-4B",
      "pitch-classes": [0, 1, 3, 4, 5, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-4",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "8-5",
      "pitch-classes": [0, 1, 2, 3, 4, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "8-5B",
      "pitch-classes": [0, 1, 2, 4, 5, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-5",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "8-6",
      "pitch-classes": [0, 1, 2, 3, 5, 6, 7, 8],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-6",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "8-7",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-7",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "8-8",
      "pitch-classes": [0, 1, 2, 3, 4, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-8",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "8-9",
      "pitch-classes": [0, 1, 2, 3, 6, 7, 8, 9],
      name: "Messiaen Mode 4",
      "carter-number": null,
      "complement-forte-code": "4-9",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "8-10",
      "pitch-classes": [0, 2, 3, 4, 5, 6, 7, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-10",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "8-11",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 7, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "8-11B",
      "pitch-classes": [0, 2, 4, 5, 6, 7, 8, 9],
      name: " Blues octatonic n.1",
      "carter-number": null,
      "complement-forte-code": "4-11",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "8-12",
      "pitch-classes": [0, 1, 3, 4, 5, 6, 7, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "8-12B",
      "pitch-classes": [0, 2, 3, 4, 5, 6, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-12B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "8-13",
      "pitch-classes": [0, 1, 2, 3, 4, 6, 7, 9],
      name: " Blues octatonic n.2",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "8-13B",
      "pitch-classes": [0, 2, 3, 5, 6, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-13",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "8-14",
      "pitch-classes": [0, 1, 2, 4, 5, 6, 7, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "8-14B",
      "pitch-classes": [0, 2, 3, 4, 5, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-14B",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "8-15",
      "pitch-classes": [0, 1, 2, 3, 4, 6, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: true,
    },
    {
      "forte-code": "8-15B",
      "pitch-classes": [0, 1, 3, 5, 6, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-15",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "8-16",
      "pitch-classes": [0, 1, 2, 3, 5, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "8-16B",
      "pitch-classes": [0, 1, 2, 4, 6, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-16",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "8-17",
      "pitch-classes": [0, 1, 3, 4, 5, 6, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-17",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "8-18",
      "pitch-classes": [0, 1, 2, 3, 5, 6, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "8-18B",
      "pitch-classes": [0, 1, 3, 4, 6, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-18",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "8-19",
      "pitch-classes": [0, 1, 2, 4, 5, 6, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "8-19B",
      "pitch-classes": [0, 1, 3, 4, 5, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-19",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "8-20",
      "pitch-classes": [0, 1, 2, 4, 5, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-20",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "8-21",
      "pitch-classes": [0, 1, 2, 3, 4, 6, 8, 10],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-21",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "8-22",
      "pitch-classes": [0, 1, 2, 3, 5, 6, 8, 10],
      name: "Bebop Ionian (2b-2)",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "8-22B",
      "pitch-classes": [0, 1, 3, 4, 5, 6, 8, 10],
      name: "Spanish octatonic",
      "carter-number": null,
      "complement-forte-code": "4-22",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "8-23",
      "pitch-classes": [0, 1, 2, 3, 5, 7, 8, 10],
      name: "Bebop mixolydian (7b-7) - Bebop Dorian (3b-3)- Octatonic quartal",
      "carter-number": null,
      "complement-forte-code": "4-23",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "8-24",
      "pitch-classes": [0, 1, 2, 4, 5, 6, 8, 10],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-24",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "8-25",
      "pitch-classes": [0, 1, 2, 4, 6, 7, 8, 10],
      name: "Messiaen Modo 6",
      "carter-number": null,
      "complement-forte-code": "4-25",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "8-26",
      "pitch-classes": [0, 1, 3, 4, 5, 7, 8, 10],
      name: "Spanish phrygian - Bebop Ionian (5-5#) -Major sixth diminished (Barry Harris) ",
      "carter-number": null,
      "complement-forte-code": "4-26",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "8-27",
      "pitch-classes": [0, 1, 2, 4, 5, 7, 8, 10],
      name: "Minor sixth diminished (Barry Harris)",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "8-27B",
      "pitch-classes": [0, 1, 3, 4, 6, 7, 8, 10],
      name: "Dominant sixth diminished (Barry Harris)",
      "carter-number": null,
      "complement-forte-code": "4-27",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "8-28",
      "pitch-classes": [0, 1, 3, 4, 6, 7, 9, 10],
      name: "Diminished scale - Octatonic scale",
      "carter-number": null,
      "complement-forte-code": "4-28",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "8-29",
      "pitch-classes": [0, 1, 2, 3, 5, 6, 7, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: true,
    },
    {
      "forte-code": "8-29B",
      "pitch-classes": [0, 2, 3, 4, 6, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "4-29",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "9-1",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 6, 7, 8],
      name: "Chromatic nonachord",
      "carter-number": null,
      "complement-forte-code": "3-1",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "9-2",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 6, 7, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "9-2B",
      "pitch-classes": [0, 2, 3, 4, 5, 6, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "3-2",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "9-3",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 6, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "9-3B",
      "pitch-classes": [0, 1, 3, 4, 5, 6, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "3-3",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "9-4",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "9-4B",
      "pitch-classes": [0, 1, 2, 4, 5, 6, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "3-4",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "9-5",
      "pitch-classes": [0, 1, 2, 3, 4, 6, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "9-5B",
      "pitch-classes": [0, 1, 2, 3, 5, 6, 7, 8, 9],
      name: null,
      "carter-number": null,
      "complement-forte-code": "3-5",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "9-6",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 6, 8, 10],
      name: null,
      "carter-number": null,
      "complement-forte-code": "3-6",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "9-7",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 7, 8, 10],
      name: "Blues nonatonic scale",
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "9-7B",
      "pitch-classes": [0, 1, 3, 4, 5, 6, 7, 8, 10],
      name: null,
      "carter-number": null,
      "complement-forte-code": "3-7",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "9-8",
      "pitch-classes": [0, 1, 2, 3, 4, 6, 7, 8, 10],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "9-8B",
      "pitch-classes": [0, 1, 2, 4, 5, 6, 7, 8, 10],
      name: null,
      "carter-number": null,
      "complement-forte-code": "3-8",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "9-9",
      "pitch-classes": [0, 1, 2, 3, 5, 6, 7, 8, 10],
      name: "Raga Ramdasi Malhar",
      "carter-number": null,
      "complement-forte-code": "3-9",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "9-10",
      "pitch-classes": [0, 1, 2, 3, 4, 6, 7, 9, 10],
      name: null,
      "carter-number": null,
      "complement-forte-code": "3-10",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "9-11",
      "pitch-classes": [0, 1, 2, 3, 5, 6, 7, 9, 10],
      name: null,
      "carter-number": null,
      "complement-forte-code": null,
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "9-11B",
      "pitch-classes": [0, 1, 2, 4, 5, 6, 7, 9, 10],
      name: " Disminished nonatonic",
      "carter-number": null,
      "complement-forte-code": "3-11",
      "documentation-link": null,
      "*": false,
      Z: false,
    },
    {
      "forte-code": "9-12",
      "pitch-classes": [0, 1, 2, 4, 5, 6, 8, 9, 10],
      name: "Tcherepnin scale",
      "carter-number": null,
      "complement-forte-code": "3-12",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "10-1",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
      name: " Chromatic decatonic scale",
      "carter-number": null,
      "complement-forte-code": "2-1",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "10-2",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 6, 7, 8, 10],
      name: null,
      "carter-number": null,
      "complement-forte-code": "2-2",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "10-3",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 6, 7, 9, 10],
      name: null,
      "carter-number": null,
      "complement-forte-code": "2-3",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "10-4",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 6, 8, 9, 10],
      name: null,
      "carter-number": null,
      "complement-forte-code": "2-4",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "10-5",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 7, 8, 9, 10],
      name: "Major/minor mixed scale",
      "carter-number": null,
      "complement-forte-code": "2-5",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "10-6",
      "pitch-classes": [0, 1, 2, 3, 4, 6, 7, 8, 9, 10],
      name: "Messiaen mode 7",
      "carter-number": null,
      "complement-forte-code": "2-6",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "11-1",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      name: "Undecatonic scale",
      "carter-number": null,
      "complement-forte-code": "1-1",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
    {
      "forte-code": "12-1",
      "pitch-classes": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
      name: "Chromatic scale",
      "carter-number": null,
      "complement-forte-code": "0-1",
      "documentation-link": null,
      "*": true,
      Z: false,
    },
  ],

  /**
   * Returns the chord with the given forte code from the `CHORDS.data` array.
   * @param {string} forteCode - The forte code of the chord to retrieve.
   * @returns {Chord | undefined} The chord with the given forte code, or undefined if no
   * chord exists with that forte code.
   */
  getByForteCode(forteCode) {
    for (let chord of this.data) {
      if (chord["forte-code"] === forteCode) {
        return chord;
      }
    }
  },

  /**
   * Returns the chord with the specified pitch classes from the `CHORDS.data` array.
   * @param {Array<number>} pitchClasses - An array of pitch classes to match.
   * @returns {Chord | undefined} The chord object if found, otherwise undefined.
   */
  getByPitchClasses(pitchClasses) {
    pitchClasses = pitchClasses.sort((a, b) => a - b);
    for (let chord of this.data) {
      chordClasses = chord["pitch-classes"].sort((a, b) => a - b);
      if (pitchClasses.length !== chordClasses.length) continue;
      for (let i = 0; i < pitchClasses.length; i++) {
        if (pitchClasses[i] !== chordClasses[i]) break;
        if (i === pitchClasses.length - 1) return chord;
      }
    }
  },

  /**
   * Returns all chords with the given cardinality from the `CHORDS.data` array.
   * @param {number} cardinality - The cardinality of the chords to retrieve.
   * @returns {Array<Chord>} An array of chord objects with the given cardinality.
   */
  getAllByCardinality(cardinality) {
    const chordsWithCardinality = [];
    for (let chord of this.data) {
      if (chord["pitch-classes"].length === cardinality)
        chordsWithCardinality.push(chord);
    }
    return chordsWithCardinality;
  },

  /**
   * Updates the documentation links for chords based on Google Drive file mapping.
   * @param {Object} fileMap - A mapping of forte-codes to Google Drive file IDs
   */
  updateDocumentationLinks(fileMap) {
    if (!fileMap || typeof fileMap !== "object") {
      console.error("Invalid file map provided");
      return;
    }

    for (let chord of this.data) {
      const forteCode = chord["forte-code"];
      if (fileMap[forteCode]) {
        chord[
          "documentation-link"
        ] = `https://drive.google.com/file/d/${fileMap[forteCode]}/view?usp=drive_link`;
      }
    }
  },
};
